platform: template
name: "Door Open Brightness [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_door_open_brightness
state_topic: "${area_id}/${device_id}/door_open_brightness"
optimistic: True
min_value: 0
max_value: 1
step: 0.01
initial_value: 0.1
mode: BOX
unit_of_measurement: "%"
restore_value: True
retain: True