platform: template
name: "Day Length Vegetative [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_day_length_vegetative
state_topic: "${area_id}/${device_id}/day_length_vegetative"
command_topic: "${area_id}/${device_id}/day_length_vegetative/set-state"
optimistic: True
initial_value: 18
min_value: 0
max_value: 24
step: 1
mode: BOX
icon: mdi:weather-sunset-up
restore_value: True
retain: True