platform: template
name: "Duration Vegetative (Days) [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_duration_vegetative
state_topic: "${area_id}/duration_vegetative/state/${device_id}"
command_topic: "${area_id}/duration_vegetative/state/${device_id}/set"
optimistic: True
min_value: 0
max_value: 365
step: 1
initial_value: 30
mode: BOX
unit_of_measurement: "days"
restore_value: True
retain: True