platform: template
name: "Duration Flipping (Days) [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_duration_flipping
state_topic: "${area_id}/${device_id}/duration_flipping"
command_topic: "${area_id}/${device_id}/duration_flipping/set-state"
optimistic: True
min_value: 0
max_value: 365
step: 1
initial_value: 10
mode: BOX
unit_of_measurement: "days"
restore_value: True
retain: True