platform: template
name: "Gantry Position Min [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_gantry_position_min
state_topic: "${area_id}/gantry_position_min"
command_topic: "${area_id}/gantry_position_min/set-state"
min_value: 0
max_value: 1
step: 0.01
initial_value: 0.2
optimistic: True
mode: BOX
restore_value: True
retain: True