platform: template
name: "Position Max [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_position_max
state_topic: "${area_id}/position_max/state/${device_id}"
command_topic: "${area_id}/position_max/state/${device_id}/set"
min_value: 0
max_value: 2
step: 0.01
initial_value: 0.2
optimistic: True
mode: BOX
restore_value: True
retain: True