platform: template
name: "DLI Generative Peak [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_dli_generative_peak
state_topic: "${area_id}/${device_id}/dli_generative_peak"
command_topic: "${area_id}/${device_id}/dli_generative_peak/set-state"
optimistic: True
initial_value: 40
min_value: 1
max_value: 100
step: 1
mode: BOX
unit_of_measurement: "mol/m2/day"
icon: mdi:weather-sunny
restore_value: True
retain: True