platform: template
name: "Duration Generative (Days) [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_duration_generative
state_topic: "${area_id}/${device_id}/duration_generative"
command_topic: "${area_id}/${device_id}/duration_generative/set-state"
optimistic: True
min_value: 0
max_value: 365
step: 1
initial_value: 50
mode: BOX
unit_of_measurement: "days"
restore_value: True
retain: True