platform: template
name: "Day Length Generative [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_day_length_generative
state_topic: "${area_id}/day_length_generative/state/${device_id}"
command_topic: "${area_id}/day_length_generative/state/${device_id}/set"
optimistic: True
initial_value: 12
min_value: 0
max_value: 24
step: 1
mode: BOX
icon: mdi:weather-sunset-up
restore_value: True
retain: True