platform: template
name: "Sunrise Time (Seconds from Midnight) [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_sunrise_time
state_topic: "${area_id}/sunrise_time/${device_id}"
command_topic: "${area_id}/sunrise_time/set-state/${device_id}"
optimistic: True
min_value: 0
max_value: 86400  # Maximum seconds in a day
step: 1
initial_value: 28800
mode: BOX
unit_of_measurement: "seconds"
restore_value: True
retain: True