platform: template
name: "Sweep Duration [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_sweep_duration
state_topic: "${area_id}/${device_id}/fan_sweep_duration"
command_topic: "${area_id}/${device_id}/fan_sweep_duration/set-state"
optimistic: true
initial_value: 60
min_value: 1
max_value: 180
step: 1
mode: BOX
unit_of_measurement: "min"
icon: mdi:timer