platform: template
name: "Irrigation Period [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_irrigation_period
state_topic: "${area_id}/irrigation_period/state/${device_id}"
command_topic: "${area_id}/irrigation_period/state/${device_id}/set"
optimistic: True
initial_value: 60
min_value: 1
max_value: 1440
step: 1
mode: BOX
unit_of_measurement: "minutes"
icon: mdi:water-pump
restore_value: True
retain: True