platform: template
name: "Position Target [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_position_target
state_topic: "${area_id}/gantry_position_target/state/${device_id}"
command_topic: "${area_id}/gantry_position_target/state/${device_id}/set"
min_value: 0.1
max_value: 1.3
step: 0.01
initial_value: 0.3
optimistic: True
mode: BOX
restore_value: True
retain: True
on_value:
    then:
    - script.execute: ${area_id}_trigger_gantry_move