platform: template
name: "Temperature Max [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_temperature_max
state_topic: "${area_id}/temperature_max/${device_id}"
command_topic: "${area_id}/temperature_max/set-state/${device_id}"
optimistic: True
initial_value: 30
min_value: 20
max_value: 35
step: 1
mode: BOX
unit_of_measurement: "°C"
icon: mdi:thermometer
restore_value: True
retain: True