id: mqtt_publish_cola_detected_false
then:
- mqtt.publish:
    topic: "${area_id}/cola_detected/${device_id}"
    payload: !lambda |-
        ESP_LOGD("mqtt_publish", "Publishing Cola Detected: false");
        return "{\"state\": \"false\"}";
