platform: bh1750
name: "Illuminance [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_illuminance
state_topic: "${area_id}/illuminance/${device_id}"
address: ${address_bh1750}
update_interval: 1s
i2c_id: bus_a
unit_of_measurement: "lx"
filters:
    - exponential_moving_average:
        alpha: 0.1  # Adjust this value for stronger or weaker , 0 to 1
        send_every: 5