platform: bme68x_bsec2
temperature:
    name: "Temperature [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_temperature
    state_topic: "${area_id}/temperature/state/${device_id}"
pressure:
    name: "Pressure [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_pressure
    state_topic: "${area_id}/pressure/state/${device_id}"
humidity:
    name: "Humidity [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_humidity
    state_topic: "${area_id}/humidity/state/${device_id}"
iaq:
    name: "IAQ [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_iaq
    state_topic: "${area_id}/iaq/state/${device_id}"
co2_equivalent:
    name: "CO2e [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_co2e
    state_topic: "${area_id}/co2e/state/${device_id}"
breath_voc_equivalent:
    name: "bVOCe [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_bvoce
    state_topic: "${area_id}/bvoce/state/${device_id}"