platform: mqtt_subscribe
name: "G1 Temperature Max [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_g1_temperature_max
topic: "G1/temperature_max/state/CANOPY"
unit_of_measurement: "°C"
