platform: template
name: "Full Spectrum Brightness [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_full_spectrum_brightness_number_sensor
state_topic: "${area_id}/${device_id}/full_spectrum_brightness"
accuracy_decimals: 2
