platform: template
id: ${area_id}_${device_id}${suffix}_sunrise_time_hours
name: "G1 Canopy Sunrise Time (Hours)"
state_topic: "${area_id}/sunrise_time_hours/state/${device_id}"
update_interval: 1h
accuracy_decimals: 2
unit_of_measurement: 'o`clock'
lambda: |-
  float seconds = id(${area_id}_${device_id}${suffix}_sunrise_time).state;
  float hours = seconds / 3600;
  return hours;