platform: mqtt_subscribe
name: "Canopy RH Target [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_canopy_rh_target
topic: "${area_id}/rh_target/state/CANOPY"
unit_of_measurement: "%"
qos: 1