platform: mqtt_subscribe
name: "Canopy Humidity [${area_id}_${device_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_full_spectrum_brightness
topic: "${area_id}/CANOPY/full_spectrum_brightness"
unit_of_measurement: "%"
qos: 1