platform: mqtt_subscribe
name: "Temperature Max [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_temperature_max
topic: "${area_id}/temperature_max/state/CANOPY"
unit_of_measurement: "°C"
qos: 1