platform: gpio
pin: ${pin_irrigation_output}
name: "Irrigation Pump [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_irrigation_pump
state_topic: "${area_id}/irrigation_pump/state/${device_id}"
command_topic: "${area_id}/irrigation_pump/state/${device_id}/set"