platform: template
name: "Enable [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_enable
optimistic: True
state_topic: "${area_id}/enable/${device_id}"
command_topic: "${area_id}/enable/set-state/${device_id}"
qos: 0
retain: True