platform: template
name: "Enable at Night [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_enable_at_night
optimistic: True
state_topic: "${area_id}/enable_at_night/${device_id}"
command_topic: "${area_id}/enable_at_night/set-state/${device_id}"
qos: 0
retain: True