platform: gpio
pin: ${pin_circulation_output}
name: "Circulation Pump [${area_id}_${device_id}${suffix}]"
id: ${area_id}_${device_id}${suffix}_circulation_pump
state_topic: "${area_id}/circulation_pump/${device_id}"
command_topic: "${area_id}/circulation_pump/set-state/${device_id}"