ssid: !secret wifi_ssid
password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#ap:
#    ssid: "${area_id}-Canopy Fallback Hotspot"
#    password: "zyRlPuMkWQ2v"