- id: '1729499698115'
  alias: G1 VPD Control Blueprint
  description: ''
  use_blueprint:
    path: growassistant/vpd_blueprint.yaml
    input:
      vpd_control_enable: input_boolean.g1_global_enable
      water_door_switch: binary_sensor.g1_water_door_switch
      vpd_target: input_number.g1_vpd_target
      vpd_sensor: sensor.g1_vpd
      intake_temperature_sensor: sensor.g1_intake_bme680_temperature
      intake_humidity_sensor: sensor.g1_intake_bme680_humidity
      canopy_temperature_sensor: sensor.g1_canopy_bme680_temperature
      canopy_humidity_sensor: sensor.g1_canopy_bme680_humidity
      rh_target_sensor: sensor.g1_rh_target
      dayphase_sensor: sensor.g1_dayphase
      temperature_offset_max_day: input_number.g1_temperature_offset_max_day
      temperature_offset_max_night: input_number.g1_temperature_offset_max_night
      previous_d_canopy_target: input_number.g1_previous_d_canopy_target
      intake_fan: fan.g1_intake_intake_fan
      exhaust_fan_1: fan.g1_exhaust_exhaust_fan_1
      exhaust_fan_2: fan.g1_exhaust_exhaust_fan_2
      humidifier_fan: fan.g1_humidifier_humidifier
      intake_fan_speed_min: input_number.g1_intake_fan_speed_min
      intake_fan_speed_max: input_number.g1_intake_fan_speed_max
      exhaust_fan_speed_min: input_number.g1_exhaust_fan_speed_min
      exhaust_fan_speed_max: input_number.g1_exhaust_fan_speed_max
      integral_intake: input_number.g1_integral_intake
      integral_exhaust: input_number.g1_integral_exhaust
      control_intake: input_number.g1_control_intake
      control_exhaust: input_number.g1_control_exhaust
      global_enable: input_boolean.g1_global_enable
      service_mode_enable: input_boolean.g1_service_mode_enable
      kp_vpd: input_number.g1_kp_vpd
      ki_vpd: input_number.g1_ki_vpd
      kd_vpd: input_number.g1_kd_vpd
      dt_vpd: input_number.g1_dt_vpd
- id: '1730500192860'
  alias: lights_off
  description: ''
  triggers:
  - trigger: time
    at: 02:00:00
  conditions: []
  actions:
  - type: turn_off
    device_id: c5ecf0c0d2ff3e67251a4a452b370396
    entity_id: 300dc2e0024a5398ad2137677d4348ef
    domain: light
  mode: single
- id: '1730500358998'
  alias: light_on
  description: ''
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - type: turn_on
    device_id: c5ecf0c0d2ff3e67251a4a452b370396
    entity_id: 300dc2e0024a5398ad2137677d4348ef
    domain: light
  mode: single
