
# Include the sensors/combined-sensors.yaml file
template: !include sensors/combined-sensors.yaml

# template: !include_dir_merge_list templates/

# homeassistant:
#   packages: !include variables.yaml

# Loads default set of integrations. Do not remove.
default_config:

http:
  server_host: "0.0.0.0"

  # Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/lovelace-multiline-text-input-card/lovelace-multiline-text-input-card.js
    - /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js

input_boolean: !include entities/input_bools.yaml
input_number: !include entities/input_numbers.yaml
input_datetime: !include entities/input_datetime.yaml
input_text: !include entities/input_texts.yaml
# input_select: !include entities/input_selects.yaml

# automation: !include automations.yaml
automation: 
  - !include automations/light_height.yaml
  - !include automations/timelapse.yaml
  - !include automations/vpd.yaml
  - !include automations/water_autopot.yaml
  - !include automations/water_circulation.yaml
  - !include automations/dli.yaml

rest_command: !include rest_commands.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
logger:
  default: warning
  logs:
    homeassistant.components.automation: debug


influxdb:
  host: localhost
  port: 8086
  database: growassistant
  username: growassistant
  password: growassistant
  max_retries: 3
  default_measurement: state

recorder:
  include:
    domains:
      - input_number
      - input_text
      - input_datetime
      - input_boolean
  # exclude:
  #   entities:
  #     - input_number.some_excluded_entity
