
# Include the entire sensors and templates folders
template:
  sensors: !include_dir_merge_list sensors/
# template: !include_dir_merge_list templates/

homeassistant:
  packages: !include variables.yaml

# Loads default set of integrations. Do not remove.
default_config:

http:
  server_host: "0.0.0.0"

  # Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/lovelace-multiline-text-input-card/lovelace-multiline-text-input-card.js
    - /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js

input_boolean: !include entities/input_bools.yaml
input_number: !include entities/input_numbers.yaml
input_datetime: !include entities/input_datetime.yaml
input_text: !include entities/input_texts.yaml
# input_select: !include entities/input_selects.yaml

automation: !include automations.yaml
rest_command: !include rest_commands.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
logger:
  default: info

influxdb:
  host: localhost
  port: 8086
  database: growassistant
  username: growassistant
  password: growassistant
  max_retries: 3
  default_measurement: state

input_text:
  g1_timestamp:
    initial: "00:00:00"

# sensor:

#   # AIR_TEMP_POT_RH
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?htu21d%20AIR_RH_POT
#     name: AIR_TEMP_RHSENSOR
#     value_template: "{{ value_json.result.status['htu21d AIR_RH_POT']['temperature'] | round(1) }}"
#     device_class: temperature
#     unit_of_measurement: "°C"
#     scan_interval: 60
#   # AIR_RH_POT
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?htu21d%20AIR_RH_POT
#     name: AIR_RH_POT
#     value_template: "{{ value_json.result.status['htu21d AIR_RH_POT']['humidity'] | round(1) }}"
#     device_class: moisture
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # EXHAUST_FAN
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20EXHAUST_FAN
#     name: Exhaust Fan
#     value_template: "{{ value_json.result.status['fan_generic EXHAUST_FAN']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # INTAKE_FAN
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20intake_fan
#     name: Intake Fan
#     value_template: "{{ value_json.result.status['fan_generic intake_fan']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # LED FANS
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20LED_FAN
#     name: LED Fans
#     value_template: "{{ value_json.result.status['fan_generic LED_FAN']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # WIND FAN
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20WIND_FAN
#     name: Wind Fan
#     value_template: "{{ value_json.result.status['fan_generic WIND_FAN']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # LED BLOOM COB
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20LED_BLOOM
#     name: LED BLOOM
#     value_template: "{{ value_json.result.status['fan_generic LED_BLOOM']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # LED VEG COB
#   - platform: rest
#     resource: http://g1.local:7125/printer/objects/query?fan_generic%20LED_VEG
#     name: LED VEG
#     value_template: "{{ value_json.result.status['fan_generic LED_VEG']['speed'] | round(2) }}"
#     # device_class: None
#     unit_of_measurement: "%"
#     scan_interval: 60

#   # sensors
#   - platform: template
#     sensors:
#       # HUMIDITY
#       combined_humidity:
#         friendly_name: "Combined Humidity"
#         unit_of_measurement: "%"
#         value_template: >
#           {% if not is_state('sensor.g1_voco_bme680_humidity', 'unavailable') and not is_state('sensor.g1_voco_bme680_humidity', 'unknown') %}
#             {{ states('sensor.g1_voco_bme680_humidity') }}
#           {% elif not is_state('sensor.air_rh_pot', 'unavailable') and not is_state('sensor.air_rh_pot', 'unknown') %}
#             {{ states('sensor.air_rh_pot') }}
#           {% else %}
#             unavailable
#           {% endif %}

#       # TEMPERATURE
#       combined_temperature:
#         friendly_name: "Combined Temperature"
#         unit_of_measurement: "°C"
#         value_template: >
#           {% if not is_state('sensor.g1_voco_bme680_temperature', 'unavailable') and not is_state('sensor.g1_voco_bme680_temperature', 'unknown') %}
#             {{ states('sensor.g1_voco_bme680_temperature') }}
#           {% elif not is_state('sensor.air_temperature_pot', 'unavailable') and not is_state('sensor.air_temperature_pot', 'unknown') %}
#             {{ states('sensor.air_temperature_pot') }}
#           {% else %}
#             unavailable
#           {% endif %}

#       g1_vpd:
#         friendly_name: "G1 VPD"
#         unit_of_measurement: "kPa"
#         value_template: >
#           {% set T = states('sensor.air_temp_pot') | float %}
#           {% set LT = states('sensor.air_temp_pot') | float - 2 %}
#           {% set RH = states('sensor.air_rh_pot') | float %}
#           {% set ASVP = 610.78 * (2.71828 ** (T / (T + 237.3) * 17.2694)) %}
#           {% set LSVP = 610.78 * (2.71828 ** (LT / (LT + 237.3) * 17.2694)) %}
#           {% set VPD = (ASVP * (1 - RH / 100))/1000 %}
#           {% set LVPD = (LSVP - (ASVP * RH / 100))/1000 %}
#           {{ LVPD | round(2) }}
#       g1_vpd_intake:
#         friendly_name: "G1 VPD Intake"
#         unit_of_measurement: "kPa"
#         value_template: >
#           {% set T = states('sensor.g1_intake_bme680_temperature') | float %}
#           {% set LT = states('sensor.g1_intake_bme680_temperature') | float - 2 %}
#           {% set RH = states('sensor.g1_intake_bme680_humidity') | float %}
          
#           {% set ASVP = 610.78 * (2.71828 ** (T / (T + 237.3) * 17.2694)) %}
#           {% set LSVP = 610.78 * (2.71828 ** (LT / (LT + 237.3) * 17.2694)) %}
#           {% set VPD = (ASVP * (1 - RH / 100))/1000 %}
#           {% set LVPD = (LSVP - (ASVP * RH / 100))/1000 %}
#           {{ LVPD | round(2) }}
#       g1_vpd_canopy:
#         friendly_name: "G1 VPD Canopy"
#         unit_of_measurement: "kPa"
#         value_template: >
#           {% set T = states('sensor.combined_temperature') | float %}
#           {% set LT = states('sensor.combined_temperature') | float - 2 %}
#           {% set RH = states('sensor.combined_humidity') | float %}
          
#           {% set ASVP = 610.78 * (2.71828 ** (T / (T + 237.3) * 17.2694)) %}
#           {% set LSVP = 610.78 * (2.71828 ** (LT / (LT + 237.3) * 17.2694)) %}
#           {% set VPD = (ASVP * (1 - RH / 100))/1000 %}
#           {% set LVPD = (LSVP - (ASVP * RH / 100))/1000 %}
#           {{ LVPD | round(2) }}

#       # g1_rh_target:
#       #   friendly_name: "G1 RH Target"
#       #   unit_of_measurement: "%"
#       #   value_template: >
#       #     {% set T = states('sensor.g1_voco_bme680_temperature') | float %}
#       #     {% set LT = states('sensor.g1_voco_bme680_temperature') | float - 2 %}
#       #     {% set ASVP = 610.78 * (2.71828 ** (T / (T + 237.3) * 17.2694)) %}
#       #     {% set LSVP = 610.78 * (2.71828 ** (LT / (LT + 237.3) * 17.2694)) %}
#       #     {% set LVPD_TARGET = states('input_number.target_vpd') | float %}
#       #     {% set RH_TARGET = (LSVP - LVPD_TARGET * 1000) / ASVP * 100 %}
#       #     {{ RH_TARGET | round(2)}}

#       g1_rh_target:
#         friendly_name: "G1 RH Target"
#         unit_of_measurement: "%"
#         value_template: >
#           {% set T = states('sensor.combined_temperature') | float %}
#           {% set LT = states('sensor.combined_temperature') | float - 2 %}
#           {% set ASVP = 610.78 * (2.71828 ** (T / (T + 237.3) * 17.2694)) %}
#           {% set LSVP = 610.78 * (2.71828 ** (LT / (LT + 237.3) * 17.2694)) %}
#           {% set LVPD_TARGET = states('input_number.target_vpd') | float %}
#           {% set RH_TARGET = (LSVP - LVPD_TARGET * 1000) / ASVP * 100 %}
#           {{ RH_TARGET | round(2)}}

#       dew_point:
#         friendly_name: "Dew Point"
#         unit_of_measurement: "°C"
#         value_template: >
#           {% set T = states('sensor.combined_temperature') | float %}
#           {% set RH = states('sensor.combined_humidity') | float %}
#           {% set a = 17.27 %}
#           {% set b = 237.7 %}
#           {% set alpha = ((a * T) / (b + T)) + (RH / 100) | log %}
#           {% set dew_point = (b * alpha) / (a - alpha) %}
#           {{ dew_point | round(1) }}