# Include the sensors/combined-sensors.yaml file
#template:
#- !include sensors/combined-sensors.yaml

# template: !include_dir_merge_list templates/

homeassistant:
  packages: !include_dir_named packages/

# Loads default set of integrations. Do not remove.
default_config:

http:
  server_host: "0.0.0.0"

  # Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/lovelace-multiline-text-input-card/lovelace-multiline-text-input-card.js
    - /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js

camera:
  - platform: ffmpeg
    name: G3V-Cam
    input: rtsp://192.168.1.158:8554/G3V/main
  
  - platform: ffmpeg
    name: G3D-Cam
    input: rtsp://192.168.1.158:8554/G3D/main
    
    
#lovelace:
#  mode: yaml

#input_boolean: !include entities/input_bools.yaml
#input_number: !include entities/input_numbers.yaml
#input_datetime: !include entities/input_datetime.yaml
#input_text: !include entities/input_texts.yaml
#input_select: !include entities/input_selects.yaml

#automation: !include automations.yaml

#rest_command: !include rest_commands.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

# Example configuration.yaml entry
logger:
  default: warning
  logs:
    homeassistant.components.automation: debug

influxdb:
  host: localhost
  port: 8086
  database: growassistant
  username: growassistant
  password: growassistant
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - switch
      - binary_sensor
      - input_number
      - input_text
      - input_datetime
      - input_boolean
      # Add other domains as needed

recorder:
  include:
    domains:
      - sensor
      - switch
      - binary_sensor
      - input_number
      - input_text
      - input_datetime
      - input_boolean
  # exclude:
  #   entities:
  #     - input_number.some_excluded_entity

automation:
  - alias: "G1 Hourly Camera Snapshot"
    id: g1_timelapse_automation
    trigger:
      - trigger: time_pattern
        minutes: 30 # Triggers at half of every hour
    action:
      - action: camera.snapshot
        data:
          entity_id: camera.g1_cam_g1_camera
          filename: "/config/www/timelapse/G1/{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
      - action: camera.snapshot
        data:
          entity_id: camera.g1_cam_g1_camera
          filename: "/config/www/timelapse/G1/lovelace.jpg"

  - alias: "G2 Hourly Camera Snapshot"
    id: g2_timelapse_automation
    trigger:
      - trigger: time_pattern
        minutes: 30 # Triggers at half of every hour
    action:
      - action: camera.snapshot
        data:
          entity_id: camera.g2_cam_profile000_mainstream
          filename: "/config/www/timelapse/G2/{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
      - action: camera.snapshot
        data:
          entity_id: camera.g2_cam_profile000_mainstream
          filename: "/config/www/timelapse/G2/lovelace.jpg"
