blueprint:
  name: VPD Control Blueprint
  description: Adjust VPD based on target VPD after a 1-minute delay.
  domain: automation
  input:
    # Cabinet-Specific Entities
    vpd_control_enable:
      name: VPD Control Enable
      selector:
        entity:
          domain: input_boolean

    water_door_switch:
      name: Water Door Switch
      selector:
        entity:
          domain: binary_sensor

    vpd_target:
      name: VPD Target
      selector:
        entity:
          domain: input_number

    vpd_sensor:
      name: VPD Sensor
      selector:
        entity:
          domain: sensor

    intake_temperature_sensor:
      name: Intake Temperature Sensor
      selector:
        entity:
          domain: sensor

    intake_humidity_sensor:
      name: Intake Humidity Sensor
      selector:
        entity:
          domain: sensor

    canopy_temperature_sensor:
      name: Canopy Temperature Sensor
      selector:
        entity:
          domain: sensor

    canopy_humidity_sensor:
      name: Canopy Humidity Sensor
      selector:
        entity:
          domain: sensor

    rh_target_sensor:
      name: RH Target Sensor
      selector:
        entity:
          domain: sensor

    dayphase_sensor:
      name: Dayphase Sensor
      selector:
        entity:
          domain: sensor

    temperature_offset_max_day:
      name: Temperature Offset Max Day
      selector:
        entity:
          domain: input_number

    temperature_offset_max_night:
      name: Temperature Offset Max Night
      selector:
        entity:
          domain: input_number

    previous_d_canopy_target:
      name: Previous d_canopy_target
      selector:
        entity:
          domain: input_number

    intake_fan:
      name: Intake Fan
      selector:
        entity:
          domain: fan

    exhaust_fan_1:
      name: Exhaust Fan 1
      selector:
        entity:
          domain: fan

    exhaust_fan_2:
      name: Exhaust Fan 2
      selector:
        entity:
          domain: fan

    humidifier_fan:
      name: Humidifier Fan
      selector:
        entity:
          domain: fan

    intake_fan_speed_min:
      name: Intake Fan Speed Min
      selector:
        entity:
          domain: input_number

    intake_fan_speed_max:
      name: Intake Fan Speed Max
      selector:
        entity:
          domain: input_number

    exhaust_fan_speed_min:
      name: Exhaust Fan Speed Min
      selector:
        entity:
          domain: input_number

    exhaust_fan_speed_max:
      name: Exhaust Fan Speed Max
      selector:
        entity:
          domain: input_number

    integral_intake:
      name: Integral Intake
      selector:
        entity:
          domain: input_number

    integral_exhaust:
      name: Integral Exhaust
      selector:
        entity:
          domain: input_number

    control_intake:
      name: Control Intake
      selector:
        entity:
          domain: input_number

    control_exhaust:
      name: Control Exhaust
      selector:
        entity:
          domain: input_number

    # Global Entities
    global_enable:
      name: Global Enable
      selector:
        entity:
          domain: input_boolean

    service_mode_enable:
      name: Service Mode Enable
      selector:
        entity:
          domain: input_boolean

    kp_vpd:
      name: Kp VPD
      selector:
        entity:
          domain: input_number

    ki_vpd:
      name: Ki VPD
      selector:
        entity:
          domain: input_number

    kd_vpd:
      name: Kd VPD
      selector:
        entity:
          domain: input_number

    dt_vpd:
      name: dt VPD
      selector:
        entity:
          domain: input_number

trigger:
  - platform: time_pattern
    minutes: '/1'
    seconds: '00'

condition:
  - condition: state
    entity_id: !input vpd_control_enable
    state: 'on'
  - condition: state
    entity_id: !input global_enable
    state: 'on'
  - condition: state
    entity_id: !input service_mode_enable
    state: 'off'
  - condition: state
    entity_id: !input water_door_switch
    state: 'off'

action:
  - variables:
      # Assign input variables to action variables
      vpd_target_entity: !input vpd_target
      vpd_sensor_entity: !input vpd_sensor
      intake_temperature_sensor_entity: !input intake_temperature_sensor
      intake_humidity_sensor_entity: !input intake_humidity_sensor
      canopy_temperature_sensor_entity: !input canopy_temperature_sensor
      canopy_humidity_sensor_entity: !input canopy_humidity_sensor
      rh_target_sensor_entity: !input rh_target_sensor
      dayphase_sensor_entity: !input dayphase_sensor
      temperature_offset_max_day_entity: !input temperature_offset_max_day
      temperature_offset_max_night_entity: !input temperature_offset_max_night
      previous_d_canopy_target_entity: !input previous_d_canopy_target
      intake_fan_entity: !input intake_fan
      exhaust_fan_1_entity: !input exhaust_fan_1
      exhaust_fan_2_entity: !input exhaust_fan_2
      humidifier_fan_entity: !input humidifier_fan
      intake_fan_speed_min_entity: !input intake_fan_speed_min
      intake_fan_speed_max_entity: !input intake_fan_speed_max
      exhaust_fan_speed_min_entity: !input exhaust_fan_speed_min
      exhaust_fan_speed_max_entity: !input exhaust_fan_speed_max
      integral_intake_entity: !input integral_intake
      integral_exhaust_entity: !input integral_exhaust
      control_intake_entity: !input control_intake
      control_exhaust_entity: !input control_exhaust
      kp_vpd_entity: !input kp_vpd
      ki_vpd_entity: !input ki_vpd
      kd_vpd_entity: !input kd_vpd
      dt_vpd_entity: !input dt_vpd

      # Now use these variables in your templates
      vpd_target: "{{ states(vpd_target_entity) | float }}"
      canopy_vpd: "{{ states(vpd_sensor_entity) | float }}"
      intake_temp: "{{ states(intake_temperature_sensor_entity) | float }}"
      intake_hum: "{{ states(intake_humidity_sensor_entity) | float }}"
      canopy_temp: "{{ states(canopy_temperature_sensor_entity) | float }}"
      canopy_hum: "{{ states(canopy_humidity_sensor_entity) | float }}"
      rh_target: "{{ states(rh_target_sensor_entity) | float }}"
      dayphase: "{{ states(dayphase_sensor_entity) | int }}"
      temperature_offset_max_day_value: "{{ states(temperature_offset_max_day_entity) | float }}"
      temperature_offset_max_night_value: "{{ states(temperature_offset_max_night_entity) | float }}"
      Kp: "{{ states(kp_vpd_entity) | float(0) }}"
      Ki: "{{ states(ki_vpd_entity) | float(0) }}"
      Kd: "{{ states(kd_vpd_entity) | float(0) }}"
      dt: "{{ states(dt_vpd_entity) | float(0) }}"
      previous_error: "{{ states(previous_d_canopy_target_entity) | float(0) }}"
      intake_fan_speed: "{{ (state_attr(intake_fan_entity, 'percentage') | float(0)) / 100 }}"
      exhaust_fan_1_speed: "{{ (state_attr(exhaust_fan_1_entity, 'percentage') | float(0)) / 100 }}"
      exhaust_fan_2_speed: "{{ (state_attr(exhaust_fan_2_entity, 'percentage') | float(0)) / 100 }}"
      humidifier_dutycycle: "{{ state_attr(humidifier_fan_entity, 'percentage') | float(0) }}"

      # Fan speed limits
      intake_fan_min: "{{ states(intake_fan_speed_min_entity) | float }}"
      intake_fan_max: "{{ states(intake_fan_speed_max_entity) | float }}"
      exhaust_fan_min: "{{ states(exhaust_fan_speed_min_entity) | float }}"
      exhaust_fan_max: "{{ states(exhaust_fan_speed_max_entity) | float }}"

      # Control logic calculations
      d_canopy_target: "{{ canopy_vpd - vpd_target }}"
      P_intake: "{{ (Kp * d_canopy_target) | abs }}"
      P_exhaust: "{{ (Kp * d_canopy_target) | abs }}"
      integral_intake_value: "{{ (states(integral_intake_entity) | float(0) + (d_canopy_target * dt)) | abs }}"
      integral_exhaust_value: "{{ (states(integral_exhaust_entity) | float(0) + (d_canopy_target * dt)) | abs }}"
      integral_limit: 0.05
      integral_intake_clamped: "{{ [integral_limit, integral_intake_value] | min }}"
      integral_exhaust_clamped: "{{ [integral_limit, integral_exhaust_value] | min }}"
      D_intake: "{{ (Kd * (d_canopy_target - previous_error) / dt) | abs }}"
      D_exhaust: "{{ (Kd * (d_canopy_target - previous_error) / dt) | abs }}"
      calculated_control_intake: "{{ (P_intake + Ki * integral_intake_clamped + D_intake) | abs }}"
      calculated_control_exhaust: "{{ (P_exhaust + Ki * integral_exhaust_clamped + D_exhaust) | abs }}"

      min_temp: 15
      max_temp: "{{ intake_temp + (temperature_offset_max_night_value if dayphase == 0 else temperature_offset_max_day_value) }}"
      t_margin: "{{ max_temp - canopy_temp }}"
      t_potential: "{{ canopy_temp - intake_temp }}"
      rh_margin: "{{ rh_target - canopy_hum }}"
      rh_potential: "{{ canopy_hum - intake_hum }}"

  # Update Control Values
  - service: input_number.set_value
    data:
      entity_id: "{{ control_intake_entity }}"
      value: "{{ calculated_control_intake }}"
  - service: input_number.set_value
    data:
      entity_id: "{{ control_exhaust_entity }}"
      value: "{{ calculated_control_exhaust }}"

  # Update Previous Error Value
  - service: input_number.set_value
    data:
      entity_id: "{{ previous_d_canopy_target_entity }}"
      value: "{{ d_canopy_target }}"

  # Update Integral Terms
  - service: input_number.set_value
    data:
      entity_id: "{{ integral_intake_entity }}"
      value: "{{ integral_intake_clamped }}"
  - service: input_number.set_value
    data:
      entity_id: "{{ integral_exhaust_entity }}"
      value: "{{ integral_exhaust_clamped }}"

  # Control Logic
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ d_canopy_target > 0 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ rh_margin > 0 }}"
                sequence:
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ humidifier_fan_entity }}"
                    data:
                      percentage: "{{ [humidifier_dutycycle + 1, 100] | min }}"
              - conditions:
                  - condition: template
                    value_template: "{{ rh_margin <= 0 }}"
                sequence:
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ humidifier_fan_entity }}"
                    data:
                      percentage: "{{ [humidifier_dutycycle - 2, 0] | max }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ t_margin < 0 }}"
                sequence:
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ intake_fan_entity }}"
                    data:
                      percentage: "{{ [ [(intake_fan_speed + calculated_control_intake) * 100, intake_fan_max ] | min, intake_fan_min ] | max }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_1_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_1_speed + calculated_control_exhaust) * 100, exhaust_fan_max ] | min, exhaust_fan_min ] | max }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_2_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_2_speed + calculated_control_exhaust) * 100, exhaust_fan_max ] | min, exhaust_fan_min ] | max }}"
              - conditions:
                  - condition: template
                    value_template: "{{ t_margin >= 0 and rh_margin > 0 }}"
                sequence:
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ intake_fan_entity }}"
                    data:
                      percentage: "{{ [ [(intake_fan_speed - calculated_control_intake) * 100, intake_fan_min ] | max, intake_fan_max ] | min }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_1_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_1_speed - calculated_control_exhaust) * 100, exhaust_fan_min ] | max, exhaust_fan_max ] | min }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_2_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_2_speed - calculated_control_exhaust) * 100, exhaust_fan_min ] | max, exhaust_fan_max ] | min }}"
      - conditions:
          - condition: template
            value_template: "{{ d_canopy_target <= 0 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ rh_margin < 0 }}"
                sequence:
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ humidifier_fan_entity }}"
                    data:
                      percentage: "{{ [humidifier_dutycycle - 2, 0] | max }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ intake_fan_entity }}"
                    data:
                      percentage: "{{ [ [(intake_fan_speed + calculated_control_intake) * 100, intake_fan_max ] | min, intake_fan_min ] | max }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_1_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_1_speed + calculated_control_exhaust) * 100, exhaust_fan_max ] | min, exhaust_fan_min ] | max }}"
                  - service: fan.set_percentage
                    target:
                      entity_id: "{{ exhaust_fan_2_entity }}"
                    data:
                      percentage: "{{ [ [(exhaust_fan_2_speed + calculated_control_exhaust) * 100, exhaust_fan_max ] | min, exhaust_fan_min ] | max }}"
