blueprint:
  name: Water Autopot Control Blueprint
  description: Controls the irrigation pump for the autopot system based on the irrigation period and duration.
  domain: automation
  input:
    global_enable:
      name: Global Enable
      selector:
        entity:
          domain: input_boolean

    irrigation_enable:
      name: Irrigation Enable
      selector:
        entity:
          domain: input_boolean

    service_mode:
      name: Service Mode
      selector:
        entity:
          domain: input_boolean

    irrigation_period:
      name: Irrigation Period
      selector:
        entity:
          domain: input_number

    irrigation_duration:
      name: Irrigation Duration
      selector:
        entity:
          domain: input_number

    irrigation_pump:
      name: Irrigation Pump
      description: Specify the entity of the irrigation pump
      selector:
        entity:
          domain: switch

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: template
    value_template: >
      {{ (now().timestamp() // 60) % (states('!input irrigation_period') | int) == 0 }}
  - condition: state
    entity_id: !input global_enable
    state: 'on'
  - condition: state
    entity_id: !input irrigation_enable
    state: 'on'
  - condition: state
    entity_id: !input service_mode
    state: 'off'

action:
  - service: switch.turn_on
    target:
      entity_id: !input irrigation_pump

  - delay: "{{ states('!input irrigation_duration') }}"

  - service: switch.turn_off
    target:
      entity_id: !input irrigation_pump
