blueprint:
  name: Light Height Control Blueprint
  description: Automates moving the light gantry every 15 minutes based on distance sensor readings.
  domain: automation
  input:
    global_enable:
      name: Global Enable
      selector:
        entity:
          domain: input_boolean

    light_height_control_enable:
      name: Light Height Control Enable
      selector:
        entity:
          domain: input_boolean

    service_mode:
      name: Service Mode
      selector:
        entity:
          domain: input_boolean

    water_door_switch:
      name: Water Door Switch
      selector:
        entity:
          domain: binary_sensor

    light_distance_sensor:
      name: Light Distance Sensor
      selector:
        entity:
          domain: sensor

    cola_detection_distance_threshold:
      name: Cola Detection Distance Threshold
      selector:
        entity:
          domain: input_number

    ultrasonic_sensor:
      name: Ultrasonic Sensor
      selector:
        entity:
          domain: sensor

trigger:
  - platform: time_pattern
    minutes: /15

condition:
  - condition: state
    entity_id: !input global_enable
    state: 'on'
  - condition: state
    entity_id: !input light_height_control_enable
    state: 'on'
  - condition: state
    entity_id: !input service_mode
    state: 'off'
  - condition: state
    entity_id: !input water_door_switch
    state: 'off'
  - condition: template
    value_template: "{{ states('!input light_distance_sensor') | float < states('!input cola_detection_distance_threshold') | float }}"
  - condition: template
    value_template: "{{ states('!input ultrasonic_sensor') | float > 0.15 }}"

action:
  - service: rest_command.move_light_up_10mm
