blueprint:
  name: Sensor Failure Validation Blueprint
  description: Sets the restart flag if any of the specified sensors fail.
  domain: automation
  input:
    restart_flag:
      name: Restart Flag
      selector:
        entity:
          domain: input_boolean

    sensor_list:
      name: List of Sensors to Monitor
      description: Specify the sensors to validate
      selector:
        entity:
          multiple: true
          domain: sensor

trigger:
  - platform: time_pattern
    minutes: '/1'

action:
  - variables:
      sensors: !input sensor_list
      failed: >
        {# Use a namespace to allow 'failed' to persist outside the loop #}
        {% set ns = namespace(failed=false) %}
        {# Loop through all sensors to check their state #}
        {% for sensor in sensors %}
          {% set state = states(sensor) %}
          {# Check if sensor is unavailable, unknown, none, or not updated in 300s #}
          {% if state in ['unavailable', 'unknown', 'none'] or
                (as_timestamp(now()) - as_timestamp(states[sensor].last_updated)) >= 300 %}
            {% set ns.failed = true %}
          {% endif %}
        {% endfor %}
        {{ ns.failed }}

  - choose:
      - conditions: "{{ failed }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input restart_flag
      - conditions: "{{ not failed }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input restart_flag
