# The entity that controls the light gantry height is defined in the input_text_devices.yaml file as light_gantry
# The light_gantry can be moved by rest command move_light_distance with input parameter distance in mm in the file _rest_commands.yaml

# 
# The automation shall run every minute
# The automation will not move the gantry if the gantry is already at the top position

# the rest command moves the light 10mm up. The rest command is defined in the rest_commands.yaml file as move_light_up_10mm


alias: Light Height Automation
id: 'automations_light_height'
description: 'This automation reads sensor.esp1_g1_light_distance_sensor every minute'
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: state
    entity_id: input_boolean.global_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.light_height_control_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.service_mode
    state: 'off'
  - condition: state
    entity_id: binary_sensor.g1_water_door_switch
    state: "off"
  - condition: template
    value_template: "{{ states('sensor.esp1_g1_light_distance_sensor') | float < states('input_number.cola_detection_distance_threshold') | float }}"
  - condition: template
    value_template: "{{ states('sensor.g1_qbar1_ultrasonic_sensor') | int > 0.15 }}"
action:
  - service: rest_command.move_light_up_10mm
