# This automation resets the whole thing to attempt to recover from a bad state. It is a last resort.

# input_boolean.restart_flag indicates that the system should be restarted. This flag is used in the main loop to restart the system if it is set to on.
# the need for restart is evaluated every 60 minutes in the main loop.
# on state indicates that the system should be restarted.
# off state indicates that the system should not be restarted.
# restarting is done by turning off and on switch.shelly_mains_switch_0


alias: "System Reset Automation"
id: "automations_reset"
description: "Reset the system if a sensor fails."
trigger:
  - platform: time_pattern
    minutes: "/60"
    seconds: 00
condition:
  - condition: state
    entity_id: input_boolean.vpd_control_enable
    state: "on"
  - condition: state
    entity_id: input_boolean.global_enable
    state: "on"
  - condition: state
    entity_id: input_boolean.service_mode
    state: "off"
  - condition: state
    entity_id: binary_sensor.g1_water_door_switch
    state: "off"

action:
  - variables:
      restart_flag: "{{ states('input_boolean.restart_flag') }}"
  - choose:
      - conditions: "{{ restart_flag == 'on' }}"
        sequence:
          - service: switch.turn_off
            entity_id: switch.shelly_mains_switch_0
          - delay: "00:00:10"
          - service: switch.turn_on
            entity_id: switch.shelly_mains_switch_0
      - conditions: "{{ restart_flag == 'off' }}"
        sequence:

