

# logic to control wind fan speed based on temperature and humidity, and dayphase
# The automation will only run if the global_enable input_boolean is on
# The global_enable input_boolean is defined in the input_bools.yaml file

# The automation will only run if the wind_enable input_boolean is on
# The wind_enable input_boolean is defined in the input_bools.yaml file

# The automation will only run if the service_mode input_boolean is off
# The service_mode input_boolean is defined in the input_bools.yaml file

# The automation will turn off the fan if the door is open
# The automation is triggered by a change in the door state
# if the door is open, the fan will be turned off without any further checks or delays


alias: Wind Fan Control
id: 'automations_wind_fan_control'
description: 'This automation adjusts the wind fan speed based on temperature, humidity, and dayphase'
trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: binary_sensor.g1_water_door_switch
condition:
  - condition: state
    entity_id: input_boolean.global_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.wind_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.service_mode
    state: 'off'

action:
  # State of the door and handling when it's open
  - variables:
      door_state: "{{ states('binary_sensor.g1_water_door_switch') }}"

  # If the door is open, turn off the fan
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ door_state == 'on' }}"
        sequence:
          - service: fan.turn_off
            target:
              entity_id: fan.g1_wind_wind_fan_1
          - service: fan.turn_off
            target:
              entity_id: fan.g1_wind_wind_fan_2

      - conditions:
          - condition: template
            value_template: "{{ door_state == 'off' }}"
        actions:
          - variables:
            # default to input_number.wind_fan_speed
            new_wind_fan_speed: "{{ states('input_number.wind_fan_speed') | int }}"

          # Set the wind fan speed based on the calculated value
          - action: fan.set_percentage
              target:
                entity_id: fan.g1_wind_wind_fan_1
              data:
                percentage: new_wind_fan_speed
          - action: fan.set_percentage
              target:
                entity_id: fan.g1_wind_wind_fan_2
              data:
                percentage: new_wind_fan_speed


