alias: Wind Fan Control
id: 'automations_wind_fan_control'
description: 'This automation adjusts the wind fan speed based on temperature, humidity, and dayphase'
trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: binary_sensor.g1_water_door_switch
condition:
  - condition: state
    entity_id: input_boolean.g1_global_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.g1_wind_enable
    state: 'on'
  - condition: state
    entity_id: input_boolean.g1_service_mode_enable
    state: 'off'

action:
  # State of the door and handling when it's open
  - variables:
      door_state: "{{ states('binary_sensor.g1_water_door_switch') }}"

  # If the door is open, turn off the fan
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ door_state == 'on' }}"
        sequence:
          - service: fan.turn_off
            target:
              entity_id: fan.g1_wind_wind_fan_1
          - service: fan.turn_off
            target:
              entity_id: fan.g1_wind_wind_fan_2

      # If the door is closed, set the fan speed
      - conditions:
          - condition: template
            value_template: "{{ door_state == 'off' }}"
        sequence:
          - variables:
              # Default to input_number.wind_fan_speed
              new_wind_fan_speed: "{{ states('input_number.g1_wind_fan_speed') | int }}"
          # Set the wind fan speed based on the calculated value
          - service: fan.set_percentage
            target:
              entity_id: fan.g1_wind_wind_fan_1
            data:
              percentage: "{{ new_wind_fan_speed }}"
          - service: fan.set_percentage
            target:
              entity_id: fan.g1_wind_wind_fan_2
            data:
              percentage: "{{ new_wind_fan_speed }}"
