esphome:
  name: esp1
  friendly_name: esp1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wwYHDZgBT+fc5ifu7hkZjOd//Ii6sSF4Dh5YSUWzfkg="

ota:
- platform: esphome
  password: "bff9e5111ce9b489ad080c58296b28ad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp1 Fallback Hotspot"
    password: "Cgb6d0vTrmIk"

captive_portal:

# # Example configuration entry for ESP32
# i2c:
#   sda: 7
#   scl: 6
#   scan: true
#   id: bus_a

# # Example configuration entry
sensor:
#   - platform: bh1750
#     name: "G1 BH1750 Illuminance"
#     address: 0x23
#     update_interval: 60s
#     i2c_id: bus_a

  - platform: ultrasonic
    trigger_pin: 1
    echo_pin: 2
    update_interval: 1s
    pulse_time: 1000us
    name: "G1 Light Distance Sensor"
    # filters:
    # - sliding_window_moving_average:
    #     window_size: 60
    #     send_every: 60