esphome:
  name: esp2
  friendly_name: esp2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ruRWUkDlw2Fi3tJMtvcwnap4YdI/LpfyRpF0l2sxc2g="

ota:
  password: "3af4e37bd51a64b3afb7b195f2b26cc1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp2 Fallback Hotspot"
    password: "23JNSThKUFvk"

captive_portal:
    
# Example configuration entry for ESP32
i2c:
  sda: GPIO9
  scl: GPIO8
  scan: true
  id: bus_a

# Example configuration entry
sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 60s