esphome:
  name: g1-brain
  friendly_name: G1_BRAIN

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "m6tg+1jKvq0HTlFdlLfrmclbyUE71qgepvQ1ZJfgvE4="

ota:
  - platform: esphome
    password: "5fc269625e006b1c4e9247350ad09a79"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Brain Fallback Hotspot"
    password: "nece0tXfk1Jg"

captive_portal:
    