esphome:
  name: g2-water
  friendly_name: G2_WATER

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+mHWAAbHIGIDXzNgvQ8Rja+Z7BHGwg481/UP0n0ix4s="

ota:
  - platform: esphome
    password: "87f9b741507ebe07e0426b911a4318a1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Water Fallback Hotspot"
    password: "GpbIc3D6A3EN"

captive_portal:
    