esphome:
  name: g1-cam
  area: G1
  friendly_name: g1_cam

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5RuIBw/2gscHfjwBMR+eahkiEavLO/tVpQjHvzy5KZ4="

ota:
  - platform: esphome
    password: "282181d157b42d8b3d15d6fa9c7f2ee2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Cam Fallback Hotspot"
    password: "aCD7QP5n9l67"

captive_portal:
  

# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: G1 Camera
  max_framerate: 1 fps
  idle_framerate: 0.1 fps
  resolution: 1600x1200
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: true
  contrast: 0
  brightness: 0
  saturation: 0
  aec_mode: AUTO

number:
  - platform: template
    name: "Canopy Timelapse Period [G1]"
    id: g1_timlapse_period
    optimistic: True
    initial_value: 60
    min_value: 1
    max_value: 1440
    step: 1
    mode: BOX
    unit_of_measurement: "minutes"
    icon: mdi:camera-timer