esphome:
  name: g1-canopy
  friendly_name: G1_CANOPY

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "w3Ll55YCHSdu8tj12EAq5Xr72upLPtEXSTI5jckiibE="

ota:
  - platform: esphome
    password: "552ee6f911d97dd2644ae7f53f972e15"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Canopy Fallback Hotspot"
    password: "zyRlPuMkWQ2v"

captive_portal:
    
  # Example configuration entry for ESP32
i2c:
  sda: 7
  scl: 6
  scan: true
  id: bus_a

# bme68x_bsec2_i2c:
#   address: 0x77
#   model: bme680
#   operating_age: 28d
#   sample_rate: LP
#   supply_voltage: 3.3V

# Example configuration entry
sensor:
  - platform: bh1750
    name: "G1 BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
    i2c_id: bus_a

  - platform: ultrasonic
    trigger_pin: 1
    echo_pin: 2
    name: "G1 Light Distance Sensor"
    update_interval: 1s
    timeout: 2m
    filters:
    - sliding_window_moving_average:
        window_size: 60
        send_every: 60

  - platform: sgp4x
    voc:
      name: "VOC Index"
    nox:
      name: "NOx Index"
    compensation:
      humidity_source: htu21d_humidity
      temperature_source: htu21d_temperature
    address: 0x59
    update_interval: 60s
    i2c_id: bus_a

  - platform: htu21d
    model: htu21d
    temperature:
      name: "Canopy Temperature"
      id: htu21d_temperature
    humidity:
      name: "Canopy Humidity"
      id: htu21d_humidity  
    heater:
      name: "Heater"

  # - platform: bme680
  #   temperature:
  #     name: "BME680 Temperature"
  #     id: bme680_temperature
  #     oversampling: 16x
  #   pressure:
  #     name: "BME680 Pressure"
  #     id: bme680_pressure
  #   humidity:
  #     name: "BME680 Humidity"
  #     id: bme680_humidity
  #   gas_resistance:
  #     name: "BME680 Gas Resistance"
  #     id: bme680_gas
  #   address: 0x76
  #   update_interval: 60s

  # - platform: bme68x_bsec2
  #   temperature:
  #     name: "BME68x Temperature"
  #   pressure:
  #     name: "BME68x Pressure"
  #   humidity:
  #     name: "BME68x Humidity"
  #   iaq:
  #     name: "BME68x IAQ"
  #     id: iaq
  #   co2_equivalent:
  #     name: "BME68x CO2 Equivalent"
  #   breath_voc_equivalent:
  #     name: "BME68x Breath VOC Equivalent"

  # - platform: bme68x_bsec2
  #   temperature:
  #     name: "BME688 Temperature"
  #     filters:
  #       - median
  #   pressure:
  #     name: "BME688 Pressure"
  #     filters:
  #       - median
  #   humidity:
  #     name: "BME688 Humidity"
  #     filters:
  #       - median
  #   iaq:
  #     name: "BME688 IAQ"
  #     filters:
  #       - median
  #   iaq_static:
  #     name: "BME688 Static IAQ"
  #     filters:
  #       - median
  #   co2_equivalent:
  #     name: "BME688 CO2 Equivalent"
  #     filters:
  #       - median
  #   breath_voc_equivalent:
  #     name: "BME688 Breath VOC Equivalent"
  #     filters:
  #       - median
  #   gas_resistance:
  #     # Gas resistance in Î©
  #     name: "BME688 Gas Resistance"
  #     filters:
  #       - median