esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable Home Assistant API
# api:
#   encryption:
#     key: "aaV/nMCt7Z7pdNZHDtFvNoL7krSrnPvIY2ucu0MJ7fQ="

ota:
  - platform: esphome
    password: "136bf7560393d6572af9c6feac1b12a7"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${area_id}-Exhaust Fallback Hotspot"
    password: "Iu5Jmv8ML5Em"

esphome:
  name: g1-exhaust

####################################################################
# configure substitutions and friendly name
####################################################################

  area: ${area_id}
  friendly_name: ${area_id}_EXHAUST${suffix}

substitutions:
  area_id: G1
  device_id: EXHAUST
  suffix: ""
  #pin_sda: 
  #pin_scl: 
  pin_fan1_pwm: GPIO7
  pin_fan2_pwm: GPIO8
  #address_bme680: "0x76"
  #bme680_temp_offset: "2.5"

####################################################################
# generic yaml for humidifiers below
####################################################################
logger:
captive_portal:
wifi:
  !include includes/wifi_default.yaml

globals:
  - id: ${area_id}_${device_id}${suffix}_fan1_pwm_value${suffix}
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${area_id}_${device_id}${suffix}_door_open${suffix}
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "${area_id}/exhaust"
  on_message:
    - topic: ${area_id}/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open${suffix}) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open${suffix}) = false;
            }
            id(update_fan_speed).execute();

output:
  - platform: ledc
    pin: ${pin_fan1_pwm}
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 0.8

  - platform: ledc
    pin: ${pin_fan2_pwm}
    id: fan2_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 0.5

fan:
  - platform: speed
    output: fan1_pwm
    name: "Exhaust [${area_id}${suffix}]"
    id: exhaust_fan1
    state_topic: "${area_id}/exhaust/fan/state"
    speed_state_topic: "${area_id}/exhaust/fan/speed"
    command_topic: "${area_id}/exhaust/fan/set-state"
    speed_command_topic: "${area_id}/exhaust/fan/set-speed"
  - platform: speed
    output: fan2_pwm
    name: "Exhaust"
    id: exhaust_fan2
    state_topic: "${area_id}/exhaust/fan/state"
    speed_state_topic: "${area_id}/exhaust/fan/speed"
    command_topic: "${area_id}/exhaust/fan/set-state"
    speed_command_topic: "${area_id}/exhaust/fan/set-speed"
    
# MQTT Sensors
sensor:
  - !include includes/sensor_mqtt_temperature_max.yaml
  - !include includes/sensor_mqtt_canopy_vpd_target.yaml
  - !include includes/sensor_mqtt_canopy_vpd.yaml
  - !include includes/sensor_mqtt_canopy_rh_target.yaml
  - !include includes/sensor_mqtt_canopy_humidity.yaml
  - !include includes/sensor_mqtt_canopy_temperature.yaml
  - !include includes/sensor_mqtt_gantry_vpd.yaml
  - !include includes/sensor_mqtt_gantry_rh_target.yaml
  - !include includes/sensor_mqtt_gantry_humidity.yaml
  - !include includes/sensor_mqtt_gantry_temperature.yaml

number:
  - !include includes/number_fan_speed_min.yaml
  - !include includes/number_fan_speed_max.yaml

interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - !include includes/script_update_fan_speed.yaml
