esphome:
  name: g1-humidifier
  friendly_name: G1_HUMIDIFIER

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "MyJ+A4snnb13Hhjtvzq5lpRLdvDePmLcLwOYc/IVnXE="

ota:
  - platform: esphome
    password: "ecf5a31fa356f2d267c8f046e257160c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Humidifier Fallback Hotspot"
    password: "ngvELfWsYHo8"

captive_portal:

globals:
  - id: humidifier_enable_state
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: door_open
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g1/humidifier"
  on_message:
    - topic: g1/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(door_open) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(door_open) = false;
            }
            id(update_fan_speed).execute();

output:
  - platform: slow_pwm
    pin: GPIO21
    id: humidifier_pwm_output
    period: 10s

fan:
  - platform: speed
    output: humidifier_pwm_output
    name: "Humidifier"
    id: humidifier_fan
    speed_count: 100  # Set the speed steps (0-100%)

sensor:
  - platform: mqtt_subscribe
    name: "Canopy RH"
    id: canopy_rh
    topic: "g1/canopy/sensor/humidity/state"
    unit_of_measurement: "%"
    qos: 1

  - platform: mqtt_subscribe
    name: "Canopy RH Target"
    id: canopy_rh_target
    topic: "g1/canopy/sensor/rh_target/state"
    unit_of_measurement: "%"
    qos: 1

  - platform: mqtt_subscribe
    name: "Gantry RH"
    id: gantry_rh
    topic: "g1/gantry/sensor/humidity/state"
    unit_of_measurement: "%"
    qos: 1

  - platform: mqtt_subscribe
    name: "Gantry RH Target"
    id: gantry_rh_target
    topic: "g1/gantry/sensor/rh_target/state"
    unit_of_measurement: "%"
    qos: 1

switch:
  - platform: template
    name: "Humidifier Enable"
    id: humidifier_enable
    optimistic: True
    state_topic: "g1/humidifier/enable"
    qos: 0
    
interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - id: update_fan_speed
    then:
      - lambda: |-
          // Check if the door is open
          if (id(door_open)) {
            // Door is open; turn off humidifier
            id(humidifier_fan).turn_off();
            ESP_LOGD("fan", "Door is open. Turning off fans.");
            return;
          }

          if (id(humidifier_enable).state) {
            auto call = id(humidifier_fan).turn_on();
            call.perform();

            float _canopy_rh_target = id(canopy_rh_target).state;
            float _gantry_rh_target = id(gantry_rh_target).state;
            float rh_target = !std::isnan(_canopy_rh_target) ? _canopy_rh_target : _gantry_rh_target;
            float rh = !std::isnan(id(canopy_rh).state) ? id(canopy_rh).state : id(gantry_rh).state;
            
            float current_speed = id(humidifier_fan).speed;
            
            if (rh_target > rh) {
              id(humidifier_fan).speed = std::min(current_speed + 0.01f, 1.0f);
            } else if (rh_target < rh) {
              //id(humidifier_fan).speed = std::max(current_speed - 0.02f, 0.0f);
              id(humidifier_fan).speed = std::max(current_speed - 2.0f, 0.0f);
            }
          } else {
            auto call = id(humidifier_fan).turn_off();
            call.perform();
          }
