esphome:
  name: g1-intake
  friendly_name: g1_intake

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "fJXKeoo4EVJYbZDSiKDT2TMY53kx7EYgg0zYEpbwMBA="

ota:
  - platform: esphome
    password: "b502f059d691352b31de26c9c4fd75c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Intake Fallback Hotspot"
    password: "iT87sU68QxKq"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g1/intake"

output:
  - platform: ledc
    pin: GPIO0
    id: fan_pwm
    frequency: 15000 Hz
    inverted: True

fan:
  - platform: speed
    output: fan_pwm
    name: "Intake"

# Example configuration entry
i2c:
  sda: GPIO20
  scl: GPIO21
  timeout: 1ms

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: 1
  
sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    iaq:
      name: "IAQ"
      id: iaq
    co2_equivalent:
      name: "CO2e"
    breath_voc_equivalent:
      name: "bVOCe"
