esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "fJXKeoo4EVJYbZDSiKDT2TMY53kx7EYgg0zYEpbwMBA="

ota:
  - platform: esphome
    password: "b502f059d691352b31de26c9c4fd75c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${area_id}-Intake Fallback Hotspot"
    password: "iT87sU68QxKq"

captive_portal:

esphome:
  name: g1-intake

####################################################################
# configure substitutions and friendly name
####################################################################

  friendly_name: ${area_id}_INTAKE${suffix}

substitutions:
  area_id: G1
  suffix: ""
  pin_fan1_pwm: GPIO0
  pin_sda: GPIO20
  pin_scl: GPIO21
  address_bme680: "0x77"
  bme680_temp_offset: "1.5"

####################################################################
# generic yaml for humidifiers below
####################################################################

globals:
  - id: ${area_id}_fan1_pwm_value${suffix}
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${area_id}_door_open${suffix}
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "${area_id}/intake"
  on_message:
    - topic: ${area_id}/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(${area_id}_door_open${suffix}) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(${area_id}_door_open${suffix}) = false;
            }
            id(update_fan_speed).execute();

output:
  - platform: ledc
    pin: ${pin_fan1_pwm}
    id: ${area_id}_fan1_pwm${suffix}
    frequency: 25000 Hz
    inverted: True

fan:
  - platform: speed
    output: ${area_id}_fan1_pwm${suffix}
    name: "Intake"
    id: intake_fan

# Example configuration entry
i2c:
  sda: ${pin_sda}
  scl: ${pin_scl}
  timeout: 1ms

bme68x_bsec2_i2c:
  address: ${address_bme680}
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: ${bme680_temp_offset}
  
sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperature"
      id: ${area_id}_intake_temperature${suffix}
      state_topic: "${area_id}/temperature/intake"
    pressure:
      name: "Pressure"
      id: ${area_id}_intake_pressure${suffix}
      state_topic: "${area_id}/pressure/intake"
    humidity:
      name: "Humidity"
      id: ${area_id}_intake_humidity${suffix}
      state_topic: "${area_id}/humidity/intake"
    iaq:
      name: "IAQ"
      id: ${area_id}_intake_iaq${suffix}
      state_topic: "${area_id}/iaq/intake"
    co2_equivalent:
      name: "CO2e"
      id: ${area_id}_intake_co2e${suffix}
      state_topic: "${area_id}/co2e/intake"
    breath_voc_equivalent:
      name: "bVOCe"
      id: ${area_id}_bvoce_intake${suffix}
      state_topic: "${area_id}/bvoce/intake"
    
# MQTT Sensors
  - platform: mqtt_subscribe
    name: "Temperature Max"
    id: ${area_id}_intake_temperature_max${suffix}
    topic: "${area_id}/temperature_max"

  - platform: mqtt_subscribe
    name: "VPD Target"
    id: ${area_id}_intake_canopy_vpd_target${suffix}
    topic: "${area_id}/vpd_target/canopy"

  - platform: mqtt_subscribe
    name: "Canopy VPD"
    id: ${area_id}_intake_canopy_vpd${suffix}
    topic: "${area_id}/vpd/canopy"

  - platform: mqtt_subscribe
    name: "Canopy RH Target"
    id: ${area_id}_intake_canopy_rh_target${suffix}
    topic: "${area_id}/rh_target/canopy"

  - platform: mqtt_subscribe
    name: "Canopy Humidity"
    id: ${area_id}_intake_canopy_humidity${suffix}
    topic: "${area_id}/humidity/canopy"

  - platform: mqtt_subscribe
    name: "Canopy Temperature"
    id: ${area_id}_intake_canopy_temperature${suffix}
    topic: "${area_id}/temperature/canopy"

  - platform: mqtt_subscribe
    name: "Gantry VPD"
    id: ${area_id}_intake_gantry_vpd${suffix}
    topic: "${area_id}/vpd/gantry"

  - platform: mqtt_subscribe
    name: "Gantry RH Target"
    id: ${area_id}_intake_gantry_rh_target${suffix}
    topic: "${area_id}//rh_target/gantry"

  - platform: mqtt_subscribe
    name: "Gantry Humidity"
    id: ${area_id}_intake_gantry_humidity${suffix}
    topic: "${area_id}/humidity/gantry"

  - platform: mqtt_subscribe
    name: "Gantry Temperature"
    id: ${area_id}_intake_gantry_temperature${suffix}
    topic: "${area_id}/temperature/gantry"

number:
  - platform: template
    name: "Intake Fan Speed Min"
    id: ${area_id}_intake_fan_speed_min${suffix}
    state_topic: "${area_id}/intake_fan_speed_min"
    command_topic: "${area_id}/intake_fan_speed_min/set-state"
    optimistic: True
    initial_value: 0.0
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    mode: box 
    unit_of_measurement: "%"
    retain: True
    restore_value: True

  - platform: template
    name: "Intake Fan Speed Max"
    id: ${area_id}_intake_fan_speed_max${suffix}
    state_topic: "${area_id}/intake_fan_speed_max"
    command_topic: "${area_id}/intake_fan_speed_max/set-state"
    optimistic: True
    initial_value: 60.0
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    mode: box 
    unit_of_measurement: "%"
    retain: True
    restore_value: True

interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - id: update_fan_speed
    then:
      lambda: |-
        // Check if the door is open
        if (id(${area_id}_door_open${suffix})) {
          // Door is open; turn off both fans
          auto call1 = id(intake_fan).turn_off();
          call1.perform();
          ESP_LOGD("fan", "Door is open. Turning off fans.");
          return;
        }

        auto call2 = id(intake_fan).turn_on();
        call2.perform();

        // Door is closed; proceed with fan speed adjustments
        // Default to gantry data
        float temperature = id(${area_id}_intake_canopy_temperature).state;
        float humidity = id(${area_id}_intake_canopy_humidity).state;
        float rh_target = id(${area_id}_intake_canopy_rh_target).state;

        // Use canopy data if available
        if (!isnan(id(${area_id}_intake_gantry_temperature).state)) {
          temperature = id(${area_id}_intake_gantry_temperature).state;
        }
        if (!isnan(id(${area_id}_intake_canopy_humidity).state)) {
          humidity = id(${area_id}_intake_gantry_humidity).state;
        }
        if (!isnan(id(${area_id}_intake_gantry_rh_target).state)) {
          rh_target = id(${area_id}_intake_gantry_rh_target).state;
        }

        // Get temperature max value
        float _temperature_max = id(${area_id}_intake_temperature_max).state;

        // Adjust fan speed based on conditions
        float fan_value = id(${area_id}_fan1_pwm_value${suffix});

        // If temperature exceeds temperature max, increase fan speed
        if (temperature > _temperature_max) {
          fan_value += 1.0;
        }

        // If humidity exceeds rh_target, increase fan speed, else decrease fan speed
        if (humidity > rh_target) {
          fan_value += 1.0;
        } else {
          fan_value -= 2.0;
        }

        // Retrieve min and max fan speeds
        float fan_min = id(${area_id}_intake_fan_speed_min).state;
        float fan_max = id(${area_id}_intake_fan_speed_max).state;

        // Clamp the fan value between min and max
        fan_value = fmax(fan_min, fmin(fan_max, fan_value));

        // Update the global fan speed value
        id(${area_id}_fan1_pwm_value${suffix}) = fan_value;

        // Set the fan speed to both fans
        id(intake_fan).speed = fan_value;

        ESP_LOGD("fan", "Updating fan speed to %.2f%% (Min: %.2f%%, Max: %.2f%%)", fan_value, fan_min, fan_max);

