esphome:
  name: g1-intake
  friendly_name: g1_intake

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fJXKeoo4EVJYbZDSiKDT2TMY53kx7EYgg0zYEpbwMBA="

ota:
  - platform: esphome
    password: "b502f059d691352b31de26c9c4fd75c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Intake Fallback Hotspot"
    password: "iT87sU68QxKq"

captive_portal:

output:
  - platform: ledc
    pin: GPIO0
    id: fan_pwm
    frequency: 15000 Hz
    inverted: True

fan:
  - platform: speed
    output: fan_pwm
    name: "Intake Fan"

# Example configuration entry
i2c:
  sda: GPIO20
  scl: GPIO21
  timeout: 1ms

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s
