esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable Home Assistant API
#api:
#  encryption:
#    key: "EJ5yzkvX09ZYh7ILJu6ykonx6gKIX8kAS8CRqDma4cc="

ota:
  - platform: esphome
    password: "42fc941ce3090d78c60ebc73f973bb3e"

esphome:
  name: g1-qbar2

####################################################################
# configure substitutions and friendly name
####################################################################

  area: ${area_id}
  friendly_name: ${area_id}_${device_id}${suffix}

substitutions:
  area_id: G1
  device_id: "QBAR"
  suffix: "_B"
  pin_light_pwm: GPIO8
  pin_sda: GPIO9
  pin_scl: GPIO10

####################################################################
# generic yaml for humidifiers below
####################################################################
logger:
captive_portal:
wifi:
  !include includes/wifi_default.yaml

i2c:
  !include includes/i2c_bus_a.yaml

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "${area_id}/${device_id}"
  log_topic: "debug/${area_id}/${device_id}"

# PWM controlled LED on GPIO8
output:
  - platform: ledc
    pin: ${pin_light_pwm}
    id: ${area_id}_${device_id}${suffix}_led_pwm
    frequency: 100 Hz 
    max_power: 0.95

light:
  - platform: monochromatic
    output: ${area_id}_${device_id}${suffix}_led_pwm
    name: "Full Spectrum [${area_id}${suffix}]"
    state_topic: "${area_id}/full_spectrum/state/${device_id}"
    command_topic: "${area_id}/full_spectrum/state/${device_id}/set"
