esphome:
  name: g1-qbar2
  friendly_name: G1_QBAR2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EJ5yzkvX09ZYh7ILJu6ykonx6gKIX8kAS8CRqDma4cc="

ota:
  - platform: esphome
    password: "42fc941ce3090d78c60ebc73f973bb3e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Qbar2 Fallback Hotspot"
    password: "Tf85Qj6WNZ11"

captive_portal:


i2c:
  sda: 9
  scl: 10
  scan: true
  id: bus_a
  # frequency: 400kHz 

# PWM controlled LED on GPIO8
output:
  - platform: ledc
    pin: GPIO8
    id: led_pwm
    frequency: 100 Hz 

light:
  - platform: monochromatic
    output: led_pwm
    name: "PWM QBAR2"

# Ultrasonic sensor on GPIO9 (TRIG) and GPIO10 (ECHO)
sensor:

  - platform: bh1750
    name: "G1 BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
    i2c_id: bus_a

  # - platform: ultrasonic
  #   trigger_pin: GPIO9
  #   echo_pin: GPIO10
  #   name: "Ultrasonic Sensor"
  #   update_interval: 1s
  #   timeout: 2m

  # - platform: bh1750
  #   name: "G1 BH1750 Illuminance"
  #   address: 0x23
  #   update_interval: 60s
  #   i2c_id: bus_a

  # - platform: ultrasonic
    # trigger_pin: 1
    # echo_pin: 2
    # update_interval: 10s
    # pulse_time: 1000us
    # name: "G1 Light Distance Sensor"
    # filters:
    # - sliding_window_moving_average:
    #     window_size: 60
    #     send_every: 60

  # - platform: bme680
  #   temperature:
  #     name: "BME680 Temperature"
  #     id: bme680_temperature
  #     oversampling: 16x
  #   pressure:
  #     name: "BME680 Pressure"
  #     id: bme680_pressure
  #   humidity:
  #     name: "BME680 Humidity"
  #     id: bme680_humidity
  #   gas_resistance:
  #     name: "BME680 Gas Resistance"
  #     id: bme680_gas
  #   address: 0x77
  #   update_interval: 60s
  #   i2c_id: bus_a