esphome:
  name: g1-water
  friendly_name: G1_WATER

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "XbvFchjTspxi0dk0Objx6+8XizJI+lwcPS6Ob2rDmD8="

ota:
  - platform: esphome
    password: "26325faebfbf96cce6b0f8453acff645"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Water Fallback Hotspot"
    password: "z1UgmdVZZnJJ"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g1/water"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    name: "Door Switch"
    state_topic: "g1/door_switch"
    device_class: door

switch:
  - platform: gpio
    pin: GPIO9
    name: "Irrigation Pump"
    id: irrigation_pump

  - platform: gpio
    pin: GPIO10
    name: "Circulation Pump"
    id: circulation_pump

  - platform: template
    name: "Water Enable"
    id: water_enable
    optimistic: true

number:
  - platform: template
    name: "Irrigation Period"
    id: g1_irrigation_period
    optimistic: True
    initial_value: 60
    min_value: 1
    max_value: 1440
    step: 1
    mode: BOX
    unit_of_measurement: "minutes"
    icon: mdi:water-pump
  
  - platform: template
    name: "Irrigation Duration"
    id: g1_irrigation_duration
    optimistic: True
    initial_value: 30
    min_value: 1
    max_value: 300
    step: 1
    mode: BOX
    unit_of_measurement: "seconds"
    icon: mdi:water-pump

  - platform: template
    name: "Circulation Period"
    id: g1_circulation_period
    optimistic: True
    initial_value: 60
    min_value: 1
    max_value: 1440
    step: 1
    mode: BOX
    unit_of_measurement: "minutes"
    icon: mdi:water-pump
  
  - platform: template
    name: "Circulation Duration"
    id: g1_circulation_duration
    optimistic: True
    initial_value: 5
    min_value: 1
    max_value: 30
    step: 1
    mode: BOX
    unit_of_measurement: "minutes"
    icon: mdi:water-pump

interval:
  # Irrigation Interval
  - interval: 1min  # This interval will check every minute
    then:
      - if:
          condition:
            lambda: 'return id(water_enable).state && (millis() / 60000) % ((int) id(g1_irrigation_period).state) == 0;'
          then:
            - switch.turn_on: irrigation_pump
            - delay: !lambda 'return (int) id(g1_irrigation_duration).state * 1000;'
            - switch.turn_off: irrigation_pump

  # Circulation Interval
  - interval: 1min  # This interval will check every minute
    then:
      - if:
          condition:
            lambda: 'return id(water_enable).state && (millis() / 60000) % ((int) id(g1_circulation_period).state) == 0;'
          then:
            - switch.turn_on: circulation_pump
            - delay: !lambda 'return (int) id(g1_circulation_duration).state * 60000;'
            - switch.turn_off: circulation_pump
