esphome:
  name: g1-water
  friendly_name: G1_WATER

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XbvFchjTspxi0dk0Objx6+8XizJI+lwcPS6Ob2rDmD8="

ota:
  - platform: esphome
    password: "26325faebfbf96cce6b0f8453acff645"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Water Fallback Hotspot"
    password: "z1UgmdVZZnJJ"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    name: "Door Switch"
    device_class: door

switch:
  - platform: gpio
    pin: GPIO9
    name: "Irrigation Pump 1"
  - platform: gpio
    pin: GPIO10
    name: "Circulation Pump 1"
