esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "qwHe3/tI5GAL34g4BySb8Mvzv26WNyzSsgS18Dx/oH0="

ota:
  - platform: esphome
    password: "0b45c8de2cc7e8951f42ac3bdaa7e4f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${area_id}-Gantry Fallback Hotspot"
    password: "G7vV59YrOf0x"

captive_portal:
    
esphome:
  name: g1-wind

####################################################################
# configure substitutions and friendly name
####################################################################

  friendly_name: ${area_id}_GANTRY${suffix}

substitutions:
  area_id: G1
  suffix: ""
  pin_sda: GPIO21
  pin_scl: GPIO20
  pin_fan1_pwm: GPIO7
  pin_fan2_pwm: GPIO8
  pin_sgp4x_address: "0x59"
  #address_bme680: "0x76"
  #bme680_temp_offset: "2.5"

####################################################################
# generic yaml for humidifiers below
####################################################################

globals:
  - id: ${area_id}_fan_speed_step${suffix}
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${area_id}_door_open${suffix}
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "${area_id}/gantry"
  on_message:
    - topic: ${area_id}/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(${area_id}_door_open${suffix}) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(${area_id}_door_open${suffix}) = false;
            }
            id(update_fan_speed).execute();

output:
  - platform: ledc
    pin: GPIO7
    id: fan1_pwm${suffix}
    frequency: 15000 Hz
    inverted: True

  - platform: ledc
    pin: GPIO8
    id: fan2_pwm${suffix}
    frequency: 15000 Hz
    inverted: True

fan:
  - platform: speed
    output: fan1_pwm
    name: "Wind"
    id: ${area_id}_wind_fan1${suffix}
  - platform: speed
    output: fan2_pwm
    name: "Wind"
    id: ${area_id}_wind_fan2${suffix}

  # Example configuration entry for ESP32
i2c:
  sda: ${pin_sda}
  scl: ${pin_scl}
  scan: true
  id: bus_a

# Example configuration entry
sensor:
  - platform: sgp4x
    voc:
      name: "Gantry VOC Index [${area_id}${suffix}]"
      state_topic: "${area_id}/voc_index/gantry"
      id: ${area_id}_gantry_voc_index${suffix}
    nox:
      name: "Gantry NOx Index [${area_id}${suffix}]"
      state_topic: "${area_id}/nox_index/gantry"
      id: ${area_id}_gantry_nox_index${suffix}
    compensation:
      humidity_source: ${area_id}_gantry_humidity${suffix}
      temperature_source: ${area_id}_gantry_temperature${suffix}
    address: ${pin_sgp4x_address}
    update_interval: 60s
    i2c_id: bus_a

  - platform: htu21d
    model: htu21d
    temperature:
      name: "Gantry Temperature [${area_id}${suffix}]"
      id: ${area_id}_gantry_temperature${suffix}
      state_topic: "${area_id}/temperature/gantry"
    humidity:
      name: "Gantry Humidity [${area_id}${suffix}]"
      id: ${area_id}_gantry_humidity${suffix}
      state_topic: "${area_id}/humidity/gantry"
    heater:
      name: "Heater"

  - platform: template
    name: "Gantry VPD [${area_id}${suffix}]"
    id: ${area_id}_gantry_vpd${suffix}
    state_topic: "${area_id}/vpd/gantry"
    unit_of_measurement: "kPa"
    update_interval: 30s
    lambda: |
      float temp = id(${area_id}_gantry_temperature${suffix}).state;
      float rh = id(${area_id}_gantry_humidity${suffix}).state;
      float leaf_offset = id(${area_id}_gantry_canopy_vpd_leaf_offset).state;
      float LT = temp + leaf_offset;
      float ASVP = 610.78 * exp((temp / (temp + 237.3)) * 17.2694);
      float LSVP = 610.78 * exp((LT / (LT + 237.3)) * 17.2694);
      float LVPD = (LSVP - (ASVP * (rh / 100.0))) / 1000.0;
      return roundf(LVPD * 100.0) / 100.0;

  - platform: template
    name: "Gantry RH Target [${area_id}${suffix}]"
    id: ${area_id}_gantry_rh_target${suffix}
    state_topic: "${area_id}/rh_target/gantry"
    unit_of_measurement: "%"
    update_interval: 30s
    lambda: |
      float T = id(${area_id}_gantry_temperature${suffix}).state;
      float LT = T - 2.0;
      float ASVP = 610.78 * pow(2.71828, (T / (T + 237.3)) * 17.2694);
      float LSVP = 610.78 * pow(2.71828, (LT / (LT + 237.3)) * 17.2694);
      float LVPD_TARGET = id(${area_id}_gantry_canopy_vpd_target${suffix}).state;
      float RH_TARGET = (LSVP - LVPD_TARGET * 1000) / ASVP * 100;
      return roundf(RH_TARGET * 10.0) / 10.0;

  - platform: template
    name: "Gantry Dew Point [${area_id}${suffix}]"
    id: ${area_id}_gantry_dew_point${suffix}
    state_topic: "${area_id}/dew_point/gantry"
    unit_of_measurement: "°C"
    update_interval: 30s
    lambda: |
      float T = id(${area_id}_gantry_temperature${suffix}).state;
      float RH = id(${area_id}_gantry_humidity${suffix}).state;
      float a = 17.27;
      float b = 237.7;
      float alpha = ((a * T) / (b + T)) + log(RH / 100.0);
      float dew_point = (b * alpha) / (a - alpha);
      return roundf(dew_point * 10.0) / 10.0;

  - platform: mqtt_subscribe
    topic: "${area_id}/vpd_leaf_offset/canopy"
    name: "Gantry VPD Leaf Offset [${area_id}${suffix}]"
    id: ${area_id}_gantry_canopy_vpd_leaf_offset${suffix}
    state_topic: "${area_id}/vpd_leaf_offset/gantry"
    retain: True

  - platform: mqtt_subscribe
    topic: "${area_id}/vpd_target/canopy"
    name: "Gantry VPD Target [${area_id}${suffix}]"
    id: ${area_id}_gantry_canopy_vpd_target${suffix}
    state_topic: "${area_id}/vpd_target/gantry"
    retain: True

number:
  - platform: template
    name: "Gantry Wind Fan Speed Min [${area_id}${suffix}]"
    id: ${area_id}_wind_fan_speed_min${suffix}
    state_topic: "${area_id}/wind_fan_speed_min"
    command_topic: "${area_id}/wind_fan_speed_min/set-state"
    optimistic: True
    initial_value: 20
    min_value: 0
    max_value: 100
    step: 1
    mode: BOX 
    unit_of_measurement: "%"
    icon: mdi:fan
    restore_value: True
    retain: True

  - platform: template
    name: "Gantry Wind Fan Speed Max [${area_id}${suffix}]"
    id: ${area_id}_wind_fan_speed_max${suffix}
    state_topic: "${area_id}/wind_fan_speed_max"
    command_topic: "${area_id}/wind_fan_speed_max/set-state"
    optimistic: True
    initial_value: 60
    min_value: 0
    max_value: 100
    step: 1
    mode: BOX 
    unit_of_measurement: "%"
    icon: mdi:fan

  - platform: template
    name: "Gantry Wind Sweep Duration [${area_id}${suffix}]"
    id: ${area_id}_wind_sweep_duration${suffix}
    state_topic: "${area_id}/wind_fan_sweep_duration"
    command_topic: "${area_id}/wind_fan_sweep_duration/set-state"
    optimistic: true
    initial_value: 60
    min_value: 1
    max_value: 180
    step: 1
    mode: BOX
    unit_of_measurement: "min"
    icon: mdi:timer

interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - id: update_fan_speed
    then:
      lambda: |-
        // Check if the door is open
        if (id(${area_id}_door_open${suffix})) {
          // Door is open; turn off both fans
          auto call3 = id(${area_id}_wind_fan1${suffix}).turn_off();
          call3.perform();
          auto call4 = id(${area_id}_wind_fan2${suffix}).turn_off();
          call4.perform();
          ESP_LOGD("fan", "Door is open. Turning off fans.");
          return;
        }

        auto call1 = id(${area_id}_wind_fan1${suffix}).turn_on();
        call1.perform();
        auto call2 = id(${area_id}_wind_fan2${suffix}).turn_on();
        call2.perform();

        int step = id(${area_id}_fan_speed_step${suffix});
        int duration = id(${area_id}_wind_sweep_duration).state; // Duration in minutes
        float min_speed = id(${area_id}_wind_fan_speed_min).state;
        float max_speed = id(${area_id}_wind_fan_speed_max).state;

        // Calculate the fan speed by linearly interpolating from min to max over 60 steps (1 hour)
        float fan_speed = min_speed + (max_speed - min_speed) * (step / (float)duration);

        // Increment the step counter, reset after 60 minutes
        id(${area_id}_fan_speed_step${suffix}) = (step + 1) % duration;

        // Set the fan speeds to the calculated value
        id(${area_id}_wind_fan1${suffix}).speed = fan_speed;
        id(${area_id}_wind_fan2${suffix}).speed = fan_speed;

        ESP_LOGD("fan", "Updating fan speed to %.2f%%", fan_speed);