esphome:
  name: g1-wind
  friendly_name: G1_GANTRY

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "qwHe3/tI5GAL34g4BySb8Mvzv26WNyzSsgS18Dx/oH0="

ota:
  - platform: esphome
    password: "0b45c8de2cc7e8951f42ac3bdaa7e4f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G1-Wind Fallback Hotspot"
    password: "G7vV59YrOf0x"

captive_portal:
    
globals:
  - id: fan_speed_step
    type: int
    restore_value: no
    initial_value: '0'
  - id: door_open
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g1/gantry"
  on_message:
    - topic: g1/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(door_open) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(door_open) = false;
            }
            id(update_fan_speed).execute();

output:
  - platform: ledc
    pin: GPIO7
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True

  - platform: ledc
    pin: GPIO8
    id: fan2_pwm
    frequency: 15000 Hz
    inverted: True

fan:
  - platform: speed
    output: fan1_pwm
    name: "Wind"
    id: g1_wind_fan1
  - platform: speed
    output: fan2_pwm
    name: "Wind"
    id: g1_wind_fan2

  # Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 20
  scan: true
  id: bus_a

# Example configuration entry
sensor:
  - platform: sgp4x
    voc:
      name: "VOC Index"
    nox:
      name: "NOx Index"
    compensation:
      humidity_source: humidity
      temperature_source: temperature
    address: 0x59
    update_interval: 60s
    i2c_id: bus_a

  - platform: htu21d
    model: htu21d
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity"
      id: humidity  
    heater:
      name: "Heater"

  - platform: template
    name: "VPD"
    id: g1_gantry_vpd
    unit_of_measurement: "kPa"
    update_interval: 30s
    lambda: |
      float temp = id(temperature).state;
      float rh = id(humidity).state;
      float leaf_offset = id(vpd_leaf_offset).state;
      float LT = temp + leaf_offset;
      float ASVP = 610.78 * exp((temp / (temp + 237.3)) * 17.2694);
      float LSVP = 610.78 * exp((LT / (LT + 237.3)) * 17.2694);
      float LVPD = (LSVP - (ASVP * (rh / 100.0))) / 1000.0;
      return roundf(LVPD * 100.0) / 100.0;

  - platform: template
    name: "RH Target"
    id: g1_gantry_rh_target
    unit_of_measurement: "%"
    update_interval: 30s
    lambda: |
      float T = id(temperature).state;
      float LT = T - 2.0;
      float ASVP = 610.78 * pow(2.71828, (T / (T + 237.3)) * 17.2694);
      float LSVP = 610.78 * pow(2.71828, (LT / (LT + 237.3)) * 17.2694);
      float LVPD_TARGET = id(vpd_target).state;
      float RH_TARGET = (LSVP - LVPD_TARGET * 1000) / ASVP * 100;
      return roundf(RH_TARGET * 10.0) / 10.0;

  - platform: template
    name: "Dew Point"
    id: g1_gantry_dew_point
    unit_of_measurement: "°C"
    update_interval: 30s
    lambda: |
      float T = id(temperature).state;
      float RH = id(humidity).state;
      float a = 17.27;
      float b = 237.7;
      float alpha = ((a * T) / (b + T)) + log(RH / 100.0);
      float dew_point = (b * alpha) / (a - alpha);
      return roundf(dew_point * 10.0) / 10.0;

  - platform: mqtt_subscribe
    topic: "g1/brain/number/vpd_leaf_offset"
    name: "VPD Leaf Offset"
    id: vpd_leaf_offset

  - platform: mqtt_subscribe
    topic: "g1/brain/number/vpd_target"
    name: "VPD Target"
    id: vpd_target

number:
  - platform: template
    name: "Wind Fan Speed Min"
    id: g1_wind_fan_speed_min
    optimistic: True
    initial_value: 20
    min_value: 0
    max_value: 100
    step: 1
    mode: BOX 
    unit_of_measurement: "%"
    icon: mdi:fan

  - platform: template
    name: "Wind Fan Speed Max"
    id: g1_wind_fan_speed_max
    optimistic: True
    initial_value: 60
    min_value: 0
    max_value: 100
    step: 1
    mode: BOX 
    unit_of_measurement: "%"
    icon: mdi:fan

  - platform: template
    name: "Wind Sweep Duration"
    id: g1_wind_sweep_duration
    optimistic: true
    initial_value: 60
    min_value: 1
    max_value: 180
    step: 1
    mode: BOX
    unit_of_measurement: "min"
    icon: mdi:timer

interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - id: update_fan_speed
    then:
      lambda: |-
        // Check if the door is open
        if (id(door_open)) {
          // Door is open; turn off both fans
          auto call3 = id(g1_wind_fan1).turn_off();
          call3.perform();
          auto call4 = id(g1_wind_fan2).turn_off();
          call4.perform();
          ESP_LOGD("fan", "Door is open. Turning off fans.");
          return;
        }

        auto call1 = id(g1_wind_fan1).turn_on();
        call1.perform();
        auto call2 = id(g1_wind_fan2).turn_on();
        call2.perform();

        int step = id(fan_speed_step);
        int duration = id(g1_wind_sweep_duration).state; // Duration in minutes
        float min_speed = id(g1_wind_fan_speed_min).state;
        float max_speed = id(g1_wind_fan_speed_max).state;

        // Calculate the fan speed by linearly interpolating from min to max over 60 steps (1 hour)
        float fan_speed = min_speed + (max_speed - min_speed) * (step / (float)duration);

        // Increment the step counter, reset after 60 minutes
        id(fan_speed_step) = (step + 1) % duration;

        // Set the fan speeds to the calculated value
        id(g1_wind_fan1).speed = fan_speed;
        id(g1_wind_fan2).speed = fan_speed;

        ESP_LOGD("fan", "Updating fan speed to %.2f%%", fan_speed);