esphome:
  name: g2-exhaust2
  friendly_name: G2_EXHAUST2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Cei7W3tXSTZCJ1gwmfn9LsVYXQ2svBA00NYav8NneBQ="

ota:
  - platform: esphome
    password: "55b5d1d47796c765a604a0f7168bbc2d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Exhaust2 Fallback Hotspot"
    password: "PVElaoAOyKbo"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  on_message:
    - topic: "g2/exhaust/fan/speed/set"
      qos: 0
      then:
        - lambda: |-
            int percent = atoi(x.c_str());
            if (percent >= 0 && percent <= 100) {
              id(exhaust_fan).set_percentage(percent);
            }

# i2c:
#   sda: 3
#   scl: 4
#   scan: true
#   id: bus_a

# bme68x_bsec2_i2c:
#   address: 0x77
#   model: bme680
#   operating_age: 28d
#   sample_rate: LP
#   supply_voltage: 3.3V
#   temperature_offset: 2.5


output:
  - platform: ledc
    pin: GPIO5
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 1

fan:
  - platform: template
    name: "Exhaust Fan 1"
    id: exhaust_fan
    speed_count: 100
    availability:
      topic: "g2-exhaust2/availability"
      payload_available: "online"
      payload_not_available: "offline"
    turn_on_action:
      - output.turn_on: fan1_pwm
      - mqtt.publish:
          topic: "g2/exhaust/fan/state/fan2"
          payload: "ON"
    turn_off_action:
      - output.turn_off: fan1_pwm
      - mqtt.publish:
          topic: "g2/exhaust/fan/state/fan2"
          payload: "OFF"
    set_percentage:
      - mqtt.publish:
          topic: "g2/exhaust/speed/fan2"
          payload: !lambda "return (int(x)).c_str();"
      - output.set_level:
          id: fan1_pwm
          level: !lambda "return x / 100.0;"



# sensor:
#   - platform: bme68x_bsec2
#     temperature:
#       name: "BME680 Temperature"
#     pressure:
#       name: "BME680 Pressure"
#     humidity:
#       name: "BME680 Humidity"
#     iaq:
#       name: "BME680 IAQ"
#       id: iaq
#     co2_equivalent:
#       name: "BME680 CO2 Equivalent"
#     breath_voc_equivalent:
#       name: "BME680 Breath VOC Equivalent"