esphome:
  name: g2-exhaust1
  friendly_name: G2_EXHAUST1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "NxxXh2HDdf/+vmOhtl2Dx0et5QuRfL5ozkDm8A04aZ0="

ota:
  - platform: esphome
    password: "ec6726c739a9331f01e4c7ef2b5f9e17"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Exhaust1 Fallback Hotspot"
    password: "fFBllyqlcT54"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g2/exhaust"

i2c:
  sda: 3
  scl: 4
  scan: true
  id: bus_a

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: 2.5
            
output:
  - platform: ledc
    pin: GPIO5
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 1

fan:
  - platform: speed
    output: fan1_pwm
    name: "Exhaust"
    speed_count: 100

sensor:
  - platform: bme68x_bsec2
    temperature:
      id: temperature
      name: "Temperature"
    pressure:
      id: pressure
      name: "Pressure"
    humidity:
      id: humidity
      name: "Humidity"
    iaq:
      id: iaq
      name: "IAQ"
    co2_equivalent:
      id: co2_equivalent
      name: "CO2e"
    breath_voc_equivalent:
      id: breath_voc_equivalent
      name: "bVOCe"
