esphome:
  name: g2-exhaust2
  friendly_name: G2_EXHAUST2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "Cei7W3tXSTZCJ1gwmfn9LsVYXQ2svBA00NYav8NneBQ="

ota:
  - platform: esphome
    password: "55b5d1d47796c765a604a0f7168bbc2d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Exhaust2 Fallback Hotspot"
    password: "PVElaoAOyKbo"

captive_portal:

globals:
  - id: fan1_pwm_value
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: door_open
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g2/exhaust"
  on_message:
    - topic: g2/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(door_open) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(door_open) = false;
            }
            id(update_fan_speed).execute();
  
output:
  - platform: ledc
    pin: GPIO5
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 1

fan:
  - platform: speed
    output: fan1_pwm
    name: "G2 Exhaust 2"
    id: g2_exhaust_fan2
    speed_count: 100


sensor:
  - platform: mqtt_subscribe
    name: "G2 Temperature Max"
    id: g2_temperature_max
    topic: "g2/brain/number/temperature_max/state"

  - platform: mqtt_subscribe
    name: "G2 VPD Target"
    id: g2_vpd_target
    topic: "g2/brain/number/vpd_target/state"

  - platform: mqtt_subscribe
    name: "G2 Canopy VPD"
    id: g2_canopy_vpd
    topic: "g2/canopy/sensor/vpd/state"

  - platform: mqtt_subscribe
    name: "G2 Canopy RH Target"
    id: g2_canopy_rh_target
    topic: "g2/canopy/sensor/rh_target/state"

  - platform: mqtt_subscribe
    name: "G2 Canopy Humidity"
    id: g2_canopy_humidity
    topic: "g2/canopy/sensor/humidity/state"

  - platform: mqtt_subscribe
    name: "G2 Canopy Temperature"
    id: g2_canopy_temperature
    topic: "g2/canopy/sensor/temperature/state"

  - platform: mqtt_subscribe
    name: "G2 Gantry VPD"
    id: g2_gantry_vpd
    topic: "g2/gantry/sensor/vpd/state"

  - platform: mqtt_subscribe
    name: "G2 Gantry RH Target"
    id: g2_gantry_rh_target
    topic: "g2/gantry/sensor/rh_target/state"

  - platform: mqtt_subscribe
    name: "G2 Gantry Humidity"
    id: g2_gantry_humidity
    topic: "g2/gantry/sensor/humidity/state"

  - platform: mqtt_subscribe
    name: "G2 Gantry Temperature"
    id: g2_gantry_temperature
    topic: "g2/gantry/sensor/temperature/state"

number:
  - platform: template
    name: "G2 Exhaust Fan Speed Min B"
    id: g2_exhaust_fan_speed_min_b
    state_topic: "g2/exhaust/number/exhaust_fan_speed_min"
    optimistic: True
    initial_value: 20.0
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    mode: box 
    unit_of_measurement: "%"
    retain: True
    restore_value: True

  - platform: template
    name: "G2 Exhaust Fan Speed Max B"
    id: g2_exhaust_fan_speed_max_b
    state_topic: "g2/exhaust/number/exhaust_fan_speed_max"
    optimistic: True
    initial_value: 60.0
    min_value: 0.0
    max_value: 100.0
    step: 1.0
    mode: box 
    unit_of_measurement: "%"
    retain: True
    restore_value: True

interval:
  - interval: 60s
    then:
      - script.execute: update_fan_speed

script:
  - id: update_fan_speed
    then:
      lambda: |-
        // Check if the door is open
        if (id(door_open)) {
          // Door is open; turn off both fans
          //id(fan1_pwm).set_level(0.0);
          //id(fan1_pwm_value) = 0.0;
          auto call3 = id(g2_exhaust_fan2).turn_off();
          call3.perform();
          ESP_LOGD("fan", "Door is open. Turning off fans.");
          return;
        }

        auto call1 = id(g2_exhaust_fan2).turn_on();
        call1.perform();

        // Door is closed; proceed with fan speed adjustments
        // Default to gantry data
        float temperature = id(g2_canopy_temperature).state;
        float humidity = id(g2_canopy_humidity).state;
        float rh_target = id(g2_canopy_rh_target).state;

        // Use canopy data if available
        if (!isnan(id(g2_gantry_temperature).state)) {
          temperature = id(g2_gantry_temperature).state;
        }
        if (!isnan(id(g2_canopy_humidity).state)) {
          humidity = id(g2_gantry_humidity).state;
        }
        if (!isnan(id(g2_gantry_rh_target).state)) {
          rh_target = id(g2_gantry_rh_target).state;
        }

        // Get temperature max value
        float _temperature_max = id(g2_temperature_max).state;

        // Adjust fan speed based on conditions
        float fan_value = id(fan1_pwm_value);

        // If temperature exceeds temperature max, increase fan speed
        if (temperature > _temperature_max) {
          fan_value += 1.0;
        }

        // If humidity exceeds rh_target, increase fan speed, else decrease fan speed
        if (humidity > rh_target) {
          fan_value += 1.0;
        } else {
          fan_value -= 2.0;
        }

        // Retrieve min and max fan speeds
        float fan_min = id(g2_exhaust_fan_speed_min_b).state;
        float fan_max = id(g2_exhaust_fan_speed_max_b).state;

        // Clamp the fan value between min and max
        fan_value = fmax(fan_min, fmin(fan_max, fan_value));

        // Update the global fan speed value
        id(fan1_pwm_value) = fan_value;

        // Set the fan speed to both fans
        //id(fan1_pwm).set_level(fan_value / 100.0);
        //id(fan2_pwm).set_level(fan_value / 100.0);

        id(g2_exhaust_fan2).speed = fan_value;

        ESP_LOGD("fan", "Updating fan speed to %.2f%% (Min: %.2f%%, Max: %.2f%%)", fan_value, fan_min, fan_max);

