esphome:
  name: g2-exhaust2
  friendly_name: G2_EXHAUST2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "Cei7W3tXSTZCJ1gwmfn9LsVYXQ2svBA00NYav8NneBQ="

ota:
  - platform: esphome
    password: "55b5d1d47796c765a604a0f7168bbc2d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Exhaust2 Fallback Hotspot"
    password: "PVElaoAOyKbo"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g2/exhaust"
  
output:
  - platform: ledc
    pin: GPIO5
    id: fan1_pwm
    frequency: 15000 Hz
    inverted: True
    max_power: 1

fan:
  - platform: speed
    output: fan1_pwm
    name: "Exhaust"
    id: exhaust_fan
    speed_count: 100