esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable Home Assistant API
#api:
#  encryption:
#    key: "HhOA1PlgbsEhARTfOVv2uCTzB9MqmctIsjiBJH6rE1k="

ota:
  - platform: esphome
    password: "8f69bc69bd62f07446b1e6c58f7b8814"

esphome:
  name: g2-humidifier

####################################################################
# configure substitutions and friendly name
####################################################################

  friendly_name: ${area_id}_${device_id}${suffix}

substitutions:
  area_id: G2
  device_id: "HUMIDIFIER"
  suffix: ""
  pin_humidifier_pwm_output: GPIO10
  pin_door_switch: GPIO20
  pin_door_switch_gnd: GPIO21

####################################################################
# generic yaml for humidifiers below
####################################################################
logger:
captive_portal:
wifi:
  !include includes/wifi_default.yaml

output:
  - platform: slow_pwm
    pin: ${pin_humidifier_pwm_output}
    id: ${area_id}_${device_id}${suffix}_pwm_output
    period: 10s

fan:
  - platform: speed
    output: ${area_id}_${device_id}${suffix}_pwm_output
    name: "Humidifier [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_humidifier
    speed_count: 100  # Set the speed steps (0-100%)
    state_topic: "${area_id}/fan/state/${device_id}"
    speed_state_topic: "${area_id}/fan/speed/${device_id}"
    command_topic: "${area_id}/${device_id}/fan/state/${device_id}/set"
    speed_command_topic: "${area_id}/fan/speed/${device_id}/set"

sensor:
  - !include includes/sensor_mqtt_canopy_humidity.yaml
  - !include includes/sensor_mqtt_canopy_rh_target.yaml
  - !include includes/sensor_mqtt_gantry_humidity.yaml
  - !include includes/sensor_mqtt_gantry_rh_target.yaml

binary_sensor:
  - !include includes/binary_sensor_door_switch.yaml

switch:
  - !include includes/switch_enable.yaml
    # G2 Humidifier HW Specific - GPIO21 is door switch GND, it is always on
  - platform: gpio
    pin: ${pin_door_switch_gnd}
    id: ${area_id}_${device_id}${suffix}_door_switch_gnd
    restore_mode: ALWAYS_ON  # GPIO21 is always on


globals:
  - id: ${area_id}_${device_id}${suffix}_door_open
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "auto/${area_id}/${device_id}"
  log_topic: "debug/${area_id}/${device_id}"
  on_message:
    - topic: ${area_id}/door_switch/#
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open) = false;
            }
            id(update_humidifier_speed).execute();

interval:
  - interval: 60s
    then:
      - script.execute: update_humidifier_speed

script:
  - !include includes/script_update_humidifier_speed.yaml

  - id: pubish_humidifier_speed
    then:
      - mqtt.publish:
          topic: "${area_id}/fan/speed/${device_id}"
          payload: !lambda |-
            return id(${area_id}_${device_id}${suffix}_humidifier).get_speed();