esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "HhOA1PlgbsEhARTfOVv2uCTzB9MqmctIsjiBJH6rE1k="

ota:
  - platform: esphome
    password: "8f69bc69bd62f07446b1e6c58f7b8814"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Humidifier Fallback Hotspot"
    password: "hUyWt72oSiTm"

captive_portal:

esphome:
  name: g2-humidifier

####################################################################
# configure substitutions and friendly name
####################################################################

  friendly_name: ${area_id}_${device_id}${suffix}

substitutions:
  area_id: G2
  device_id: "HUMIDIFIER"
  suffix: ""
  pin_humidifier_pwm_output: GPIO10
  pin_door_switch: GPIO20

####################################################################
# generic yaml for humidifiers below
####################################################################
logger:
captive_portal:
wifi:
  !include includes/wifi_default.yaml

output:
  - platform: slow_pwm
    pin: ${pin_humidifier_pwm_output}
    id: ${area_id}_${device_id}${suffix}_pwm_output
    period: 10s

fan:
  - platform: speed
    output: ${area_id}_${device_id}${suffix}_pwm_output
    name: "Humidifier [${area_id}_${device_id}${suffix}]"
    id: ${area_id}_${device_id}${suffix}_humidifier
    state_topic: "${area_id}/${device_id}/fan/vapor/state"
    speed_state_topic: "${area_id}/${device_id}/fan/vapor/speed"
    speed_level_state_topic: "${area_id}/${device_id}/fan/vapor/level"
    command_topic: "${area_id}/${device_id}/fan/vapor/set_state"
    speed_command_topic: "${area_id}/${device_id}/fan/vapor/set_speed"
    speed_level_command_topic: "${area_id}/${device_id}/fan/vapor/set_level"
    speed_count: 100  # Set the speed steps (0-100%)

sensor:
  - !include includes/sensor_mqtt_canopy_humidity.yaml
  - !include includes/sensor_mqtt_canopy_rh_target.yaml
  - !include includes/sensor_mqtt_gantry_humidity.yaml
  - !include includes/sensor_mqtt_gantry_rh_target.yaml

switch:
  - !include includes/switch_enable.yaml

globals:
  - id: ${area_id}_${device_id}${suffix}_door_open
    type: bool
    restore_value: no
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "${area_id}/${device_id}"
  on_message:
    - topic: ${area_id}/door_switch
      then:
        - lambda: |-
            if (strcmp(x.c_str(), "ON") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open) = true;
            } else if (strcmp(x.c_str(), "OFF") == 0) {
              id(${area_id}_${device_id}${suffix}_door_open) = false;
            }
            id(update_humidifier_speed).execute();

interval:
  - interval: 60s
    then:
      - script.execute: update_humidifier_speed

script:
  - !include includes/script_update_humidifier_speed.yaml