esphome:
  name: g2-water
  friendly_name: G2_WATER

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: "afF+LRRn2xJxO47lHzfxHAOmZksYw4lmOAZt1J83fxs="

ota:
  - platform: esphome
    password: "dc90a879c18e4b2a08e6faaa40a22be4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "G2-Water Fallback Hotspot"
    password: "hscwfhyDtBvQ"

captive_portal:
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "g2/water"

switch:
  - platform: gpio
    pin: GPIO16
    name: "Irrigation Pump"
    id: relay_1

  - platform: gpio
    pin: GPIO17
    name: "Circulation Pump"
    id: relay_2
