esphome:
  name: gx-sht21
  friendly_name: GX_SHT21

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tTsVnmfwRjAJVXiTaDmPlbupV93rhvXhWV2fzj3TVeI="

ota:
  - platform: esphome
    password: "76ea25f7bae7cb81d7e0bdf9f26644b7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gx-Sht21 Fallback Hotspot"
    password: "uWezis5Q2NxQ"

captive_portal:

i2c:
  sda: 6
  scl: 5
  scan: true
  id: bus_a
  frequency: 50kHz

switch:
  - platform: gpio
    pin: GPIO4
    id: sht_gnd
    restore_mode: ALWAYS_OFF  # GPIO4 is always on, it is GND for SHT21

sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 30s

  - platform: bh1750
    name: "G1 BH1750 Illuminance"
    address: 0x23
    update_interval: 1s
    i2c_id: bus_a
    filters:
      - exponential_moving_average:
          alpha: 0.1  # Adjust this value for stronger or weaker , 0 to 1
          send_every: 5

  - platform: ultrasonic
    trigger_pin: 8
    echo_pin: 7
    name: "G1 Light Distance Sensor"
    update_interval: 1s
    timeout: 2m
    filters:
    - sliding_window_moving_average:
        window_size: 60
        send_every: 60